// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: src/main/protobuf/css_metadata.proto
// Protobuf Java Version: 4.28.2

package com.google.template.soy.css;

public interface CssMetadataOrBuilder extends
    // @@protoc_insertion_point(interface_extends:soy.compiler.CssMetadata)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * All the namespaces required by soy files or templates
   * </pre>
   *
   * <code>repeated string require_css_names = 1;</code>
   * @return A list containing the requireCssNames.
   */
  java.util.List<java.lang.String>
      getRequireCssNamesList();
  /**
   * <pre>
   * All the namespaces required by soy files or templates
   * </pre>
   *
   * <code>repeated string require_css_names = 1;</code>
   * @return The count of requireCssNames.
   */
  int getRequireCssNamesCount();
  /**
   * <pre>
   * All the namespaces required by soy files or templates
   * </pre>
   *
   * <code>repeated string require_css_names = 1;</code>
   * @param index The index of the element to return.
   * @return The requireCssNames at the given index.
   */
  java.lang.String getRequireCssNames(int index);
  /**
   * <pre>
   * All the namespaces required by soy files or templates
   * </pre>
   *
   * <code>repeated string require_css_names = 1;</code>
   * @param index The index of the value to return.
   * @return The bytes of the requireCssNames at the given index.
   */
  com.google.protobuf.ByteString
      getRequireCssNamesBytes(int index);

  /**
   * <pre>
   * All the class names renamed with the css() function
   * </pre>
   *
   * <code>repeated string css_class_names = 2;</code>
   * @return A list containing the cssClassNames.
   */
  java.util.List<java.lang.String>
      getCssClassNamesList();
  /**
   * <pre>
   * All the class names renamed with the css() function
   * </pre>
   *
   * <code>repeated string css_class_names = 2;</code>
   * @return The count of cssClassNames.
   */
  int getCssClassNamesCount();
  /**
   * <pre>
   * All the class names renamed with the css() function
   * </pre>
   *
   * <code>repeated string css_class_names = 2;</code>
   * @param index The index of the element to return.
   * @return The cssClassNames at the given index.
   */
  java.lang.String getCssClassNames(int index);
  /**
   * <pre>
   * All the class names renamed with the css() function
   * </pre>
   *
   * <code>repeated string css_class_names = 2;</code>
   * @param index The index of the value to return.
   * @return The bytes of the cssClassNames at the given index.
   */
  com.google.protobuf.ByteString
      getCssClassNamesBytes(int index);
}
