// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: src/main/protobuf/css_metadata.proto
// Protobuf Java Version: 4.28.2

package com.google.template.soy.css;

/**
 * <pre>
 * Data about how a soy library uses CSS
 * </pre>
 *
 * Protobuf type {@code soy.compiler.CssMetadata}
 */
public final class CssMetadata extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:soy.compiler.CssMetadata)
    CssMetadataOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 28,
      /* patch= */ 2,
      /* suffix= */ "",
      CssMetadata.class.getName());
  }
  // Use CssMetadata.newBuilder() to construct.
  private CssMetadata(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private CssMetadata() {
    requireCssNames_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
    cssClassNames_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.google.template.soy.css.CssMetadataProto.internal_static_soy_compiler_CssMetadata_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.google.template.soy.css.CssMetadataProto.internal_static_soy_compiler_CssMetadata_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.google.template.soy.css.CssMetadata.class, com.google.template.soy.css.CssMetadata.Builder.class);
  }

  public static final int REQUIRE_CSS_NAMES_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private com.google.protobuf.LazyStringArrayList requireCssNames_ =
      com.google.protobuf.LazyStringArrayList.emptyList();
  /**
   * <pre>
   * All the namespaces required by soy files or templates
   * </pre>
   *
   * <code>repeated string require_css_names = 1;</code>
   * @return A list containing the requireCssNames.
   */
  public com.google.protobuf.ProtocolStringList
      getRequireCssNamesList() {
    return requireCssNames_;
  }
  /**
   * <pre>
   * All the namespaces required by soy files or templates
   * </pre>
   *
   * <code>repeated string require_css_names = 1;</code>
   * @return The count of requireCssNames.
   */
  public int getRequireCssNamesCount() {
    return requireCssNames_.size();
  }
  /**
   * <pre>
   * All the namespaces required by soy files or templates
   * </pre>
   *
   * <code>repeated string require_css_names = 1;</code>
   * @param index The index of the element to return.
   * @return The requireCssNames at the given index.
   */
  public java.lang.String getRequireCssNames(int index) {
    return requireCssNames_.get(index);
  }
  /**
   * <pre>
   * All the namespaces required by soy files or templates
   * </pre>
   *
   * <code>repeated string require_css_names = 1;</code>
   * @param index The index of the value to return.
   * @return The bytes of the requireCssNames at the given index.
   */
  public com.google.protobuf.ByteString
      getRequireCssNamesBytes(int index) {
    return requireCssNames_.getByteString(index);
  }

  public static final int CSS_CLASS_NAMES_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private com.google.protobuf.LazyStringArrayList cssClassNames_ =
      com.google.protobuf.LazyStringArrayList.emptyList();
  /**
   * <pre>
   * All the class names renamed with the css() function
   * </pre>
   *
   * <code>repeated string css_class_names = 2;</code>
   * @return A list containing the cssClassNames.
   */
  public com.google.protobuf.ProtocolStringList
      getCssClassNamesList() {
    return cssClassNames_;
  }
  /**
   * <pre>
   * All the class names renamed with the css() function
   * </pre>
   *
   * <code>repeated string css_class_names = 2;</code>
   * @return The count of cssClassNames.
   */
  public int getCssClassNamesCount() {
    return cssClassNames_.size();
  }
  /**
   * <pre>
   * All the class names renamed with the css() function
   * </pre>
   *
   * <code>repeated string css_class_names = 2;</code>
   * @param index The index of the element to return.
   * @return The cssClassNames at the given index.
   */
  public java.lang.String getCssClassNames(int index) {
    return cssClassNames_.get(index);
  }
  /**
   * <pre>
   * All the class names renamed with the css() function
   * </pre>
   *
   * <code>repeated string css_class_names = 2;</code>
   * @param index The index of the value to return.
   * @return The bytes of the cssClassNames at the given index.
   */
  public com.google.protobuf.ByteString
      getCssClassNamesBytes(int index) {
    return cssClassNames_.getByteString(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < requireCssNames_.size(); i++) {
      com.google.protobuf.GeneratedMessage.writeString(output, 1, requireCssNames_.getRaw(i));
    }
    for (int i = 0; i < cssClassNames_.size(); i++) {
      com.google.protobuf.GeneratedMessage.writeString(output, 2, cssClassNames_.getRaw(i));
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    {
      int dataSize = 0;
      for (int i = 0; i < requireCssNames_.size(); i++) {
        dataSize += computeStringSizeNoTag(requireCssNames_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getRequireCssNamesList().size();
    }
    {
      int dataSize = 0;
      for (int i = 0; i < cssClassNames_.size(); i++) {
        dataSize += computeStringSizeNoTag(cssClassNames_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getCssClassNamesList().size();
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.google.template.soy.css.CssMetadata)) {
      return super.equals(obj);
    }
    com.google.template.soy.css.CssMetadata other = (com.google.template.soy.css.CssMetadata) obj;

    if (!getRequireCssNamesList()
        .equals(other.getRequireCssNamesList())) return false;
    if (!getCssClassNamesList()
        .equals(other.getCssClassNamesList())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getRequireCssNamesCount() > 0) {
      hash = (37 * hash) + REQUIRE_CSS_NAMES_FIELD_NUMBER;
      hash = (53 * hash) + getRequireCssNamesList().hashCode();
    }
    if (getCssClassNamesCount() > 0) {
      hash = (37 * hash) + CSS_CLASS_NAMES_FIELD_NUMBER;
      hash = (53 * hash) + getCssClassNamesList().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.google.template.soy.css.CssMetadata parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.google.template.soy.css.CssMetadata parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.google.template.soy.css.CssMetadata parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.google.template.soy.css.CssMetadata parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.google.template.soy.css.CssMetadata parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.google.template.soy.css.CssMetadata parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.google.template.soy.css.CssMetadata parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.google.template.soy.css.CssMetadata parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.google.template.soy.css.CssMetadata parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.google.template.soy.css.CssMetadata parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.google.template.soy.css.CssMetadata parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.google.template.soy.css.CssMetadata parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.google.template.soy.css.CssMetadata prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * Data about how a soy library uses CSS
   * </pre>
   *
   * Protobuf type {@code soy.compiler.CssMetadata}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:soy.compiler.CssMetadata)
      com.google.template.soy.css.CssMetadataOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.google.template.soy.css.CssMetadataProto.internal_static_soy_compiler_CssMetadata_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.google.template.soy.css.CssMetadataProto.internal_static_soy_compiler_CssMetadata_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.google.template.soy.css.CssMetadata.class, com.google.template.soy.css.CssMetadata.Builder.class);
    }

    // Construct using com.google.template.soy.css.CssMetadata.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      requireCssNames_ =
          com.google.protobuf.LazyStringArrayList.emptyList();
      cssClassNames_ =
          com.google.protobuf.LazyStringArrayList.emptyList();
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.google.template.soy.css.CssMetadataProto.internal_static_soy_compiler_CssMetadata_descriptor;
    }

    @java.lang.Override
    public com.google.template.soy.css.CssMetadata getDefaultInstanceForType() {
      return com.google.template.soy.css.CssMetadata.getDefaultInstance();
    }

    @java.lang.Override
    public com.google.template.soy.css.CssMetadata build() {
      com.google.template.soy.css.CssMetadata result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.google.template.soy.css.CssMetadata buildPartial() {
      com.google.template.soy.css.CssMetadata result = new com.google.template.soy.css.CssMetadata(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.google.template.soy.css.CssMetadata result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        requireCssNames_.makeImmutable();
        result.requireCssNames_ = requireCssNames_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        cssClassNames_.makeImmutable();
        result.cssClassNames_ = cssClassNames_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.google.template.soy.css.CssMetadata) {
        return mergeFrom((com.google.template.soy.css.CssMetadata)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.google.template.soy.css.CssMetadata other) {
      if (other == com.google.template.soy.css.CssMetadata.getDefaultInstance()) return this;
      if (!other.requireCssNames_.isEmpty()) {
        if (requireCssNames_.isEmpty()) {
          requireCssNames_ = other.requireCssNames_;
          bitField0_ |= 0x00000001;
        } else {
          ensureRequireCssNamesIsMutable();
          requireCssNames_.addAll(other.requireCssNames_);
        }
        onChanged();
      }
      if (!other.cssClassNames_.isEmpty()) {
        if (cssClassNames_.isEmpty()) {
          cssClassNames_ = other.cssClassNames_;
          bitField0_ |= 0x00000002;
        } else {
          ensureCssClassNamesIsMutable();
          cssClassNames_.addAll(other.cssClassNames_);
        }
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();
              ensureRequireCssNamesIsMutable();
              requireCssNames_.add(s);
              break;
            } // case 10
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();
              ensureCssClassNamesIsMutable();
              cssClassNames_.add(s);
              break;
            } // case 18
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private com.google.protobuf.LazyStringArrayList requireCssNames_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
    private void ensureRequireCssNamesIsMutable() {
      if (!requireCssNames_.isModifiable()) {
        requireCssNames_ = new com.google.protobuf.LazyStringArrayList(requireCssNames_);
      }
      bitField0_ |= 0x00000001;
    }
    /**
     * <pre>
     * All the namespaces required by soy files or templates
     * </pre>
     *
     * <code>repeated string require_css_names = 1;</code>
     * @return A list containing the requireCssNames.
     */
    public com.google.protobuf.ProtocolStringList
        getRequireCssNamesList() {
      requireCssNames_.makeImmutable();
      return requireCssNames_;
    }
    /**
     * <pre>
     * All the namespaces required by soy files or templates
     * </pre>
     *
     * <code>repeated string require_css_names = 1;</code>
     * @return The count of requireCssNames.
     */
    public int getRequireCssNamesCount() {
      return requireCssNames_.size();
    }
    /**
     * <pre>
     * All the namespaces required by soy files or templates
     * </pre>
     *
     * <code>repeated string require_css_names = 1;</code>
     * @param index The index of the element to return.
     * @return The requireCssNames at the given index.
     */
    public java.lang.String getRequireCssNames(int index) {
      return requireCssNames_.get(index);
    }
    /**
     * <pre>
     * All the namespaces required by soy files or templates
     * </pre>
     *
     * <code>repeated string require_css_names = 1;</code>
     * @param index The index of the value to return.
     * @return The bytes of the requireCssNames at the given index.
     */
    public com.google.protobuf.ByteString
        getRequireCssNamesBytes(int index) {
      return requireCssNames_.getByteString(index);
    }
    /**
     * <pre>
     * All the namespaces required by soy files or templates
     * </pre>
     *
     * <code>repeated string require_css_names = 1;</code>
     * @param index The index to set the value at.
     * @param value The requireCssNames to set.
     * @return This builder for chaining.
     */
    public Builder setRequireCssNames(
        int index, java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      ensureRequireCssNamesIsMutable();
      requireCssNames_.set(index, value);
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * All the namespaces required by soy files or templates
     * </pre>
     *
     * <code>repeated string require_css_names = 1;</code>
     * @param value The requireCssNames to add.
     * @return This builder for chaining.
     */
    public Builder addRequireCssNames(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      ensureRequireCssNamesIsMutable();
      requireCssNames_.add(value);
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * All the namespaces required by soy files or templates
     * </pre>
     *
     * <code>repeated string require_css_names = 1;</code>
     * @param values The requireCssNames to add.
     * @return This builder for chaining.
     */
    public Builder addAllRequireCssNames(
        java.lang.Iterable<java.lang.String> values) {
      ensureRequireCssNamesIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, requireCssNames_);
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * All the namespaces required by soy files or templates
     * </pre>
     *
     * <code>repeated string require_css_names = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearRequireCssNames() {
      requireCssNames_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
      bitField0_ = (bitField0_ & ~0x00000001);;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * All the namespaces required by soy files or templates
     * </pre>
     *
     * <code>repeated string require_css_names = 1;</code>
     * @param value The bytes of the requireCssNames to add.
     * @return This builder for chaining.
     */
    public Builder addRequireCssNamesBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      ensureRequireCssNamesIsMutable();
      requireCssNames_.add(value);
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private com.google.protobuf.LazyStringArrayList cssClassNames_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
    private void ensureCssClassNamesIsMutable() {
      if (!cssClassNames_.isModifiable()) {
        cssClassNames_ = new com.google.protobuf.LazyStringArrayList(cssClassNames_);
      }
      bitField0_ |= 0x00000002;
    }
    /**
     * <pre>
     * All the class names renamed with the css() function
     * </pre>
     *
     * <code>repeated string css_class_names = 2;</code>
     * @return A list containing the cssClassNames.
     */
    public com.google.protobuf.ProtocolStringList
        getCssClassNamesList() {
      cssClassNames_.makeImmutable();
      return cssClassNames_;
    }
    /**
     * <pre>
     * All the class names renamed with the css() function
     * </pre>
     *
     * <code>repeated string css_class_names = 2;</code>
     * @return The count of cssClassNames.
     */
    public int getCssClassNamesCount() {
      return cssClassNames_.size();
    }
    /**
     * <pre>
     * All the class names renamed with the css() function
     * </pre>
     *
     * <code>repeated string css_class_names = 2;</code>
     * @param index The index of the element to return.
     * @return The cssClassNames at the given index.
     */
    public java.lang.String getCssClassNames(int index) {
      return cssClassNames_.get(index);
    }
    /**
     * <pre>
     * All the class names renamed with the css() function
     * </pre>
     *
     * <code>repeated string css_class_names = 2;</code>
     * @param index The index of the value to return.
     * @return The bytes of the cssClassNames at the given index.
     */
    public com.google.protobuf.ByteString
        getCssClassNamesBytes(int index) {
      return cssClassNames_.getByteString(index);
    }
    /**
     * <pre>
     * All the class names renamed with the css() function
     * </pre>
     *
     * <code>repeated string css_class_names = 2;</code>
     * @param index The index to set the value at.
     * @param value The cssClassNames to set.
     * @return This builder for chaining.
     */
    public Builder setCssClassNames(
        int index, java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      ensureCssClassNamesIsMutable();
      cssClassNames_.set(index, value);
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * All the class names renamed with the css() function
     * </pre>
     *
     * <code>repeated string css_class_names = 2;</code>
     * @param value The cssClassNames to add.
     * @return This builder for chaining.
     */
    public Builder addCssClassNames(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      ensureCssClassNamesIsMutable();
      cssClassNames_.add(value);
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * All the class names renamed with the css() function
     * </pre>
     *
     * <code>repeated string css_class_names = 2;</code>
     * @param values The cssClassNames to add.
     * @return This builder for chaining.
     */
    public Builder addAllCssClassNames(
        java.lang.Iterable<java.lang.String> values) {
      ensureCssClassNamesIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, cssClassNames_);
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * All the class names renamed with the css() function
     * </pre>
     *
     * <code>repeated string css_class_names = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearCssClassNames() {
      cssClassNames_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
      bitField0_ = (bitField0_ & ~0x00000002);;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * All the class names renamed with the css() function
     * </pre>
     *
     * <code>repeated string css_class_names = 2;</code>
     * @param value The bytes of the cssClassNames to add.
     * @return This builder for chaining.
     */
    public Builder addCssClassNamesBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      ensureCssClassNamesIsMutable();
      cssClassNames_.add(value);
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:soy.compiler.CssMetadata)
  }

  // @@protoc_insertion_point(class_scope:soy.compiler.CssMetadata)
  private static final com.google.template.soy.css.CssMetadata DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.google.template.soy.css.CssMetadata();
  }

  public static com.google.template.soy.css.CssMetadata getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<CssMetadata>
      PARSER = new com.google.protobuf.AbstractParser<CssMetadata>() {
    @java.lang.Override
    public CssMetadata parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<CssMetadata> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<CssMetadata> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.template.soy.css.CssMetadata getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

