// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: src/main/protobuf/annotated_logging_config.proto
// Protobuf Java Version: 4.28.2

package com.google.template.soy.logging;

public interface AnnotatedLoggableElementOrBuilder extends
    // @@protoc_insertion_point(interface_extends:soy.AnnotatedLoggableElement)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * The actual LoggableElement.
   * </pre>
   *
   * <code>optional .soy.LoggableElement element = 1;</code>
   * @return Whether the element field is set.
   */
  boolean hasElement();
  /**
   * <pre>
   * The actual LoggableElement.
   * </pre>
   *
   * <code>optional .soy.LoggableElement element = 1;</code>
   * @return The element.
   */
  com.google.template.soy.logging.LoggableElement getElement();
  /**
   * <pre>
   * The actual LoggableElement.
   * </pre>
   *
   * <code>optional .soy.LoggableElement element = 1;</code>
   */
  com.google.template.soy.logging.LoggableElementOrBuilder getElementOrBuilder();

  /**
   * <pre>
   * Whether this element has VE metadata set.
   * </pre>
   *
   * <code>optional bool has_metadata = 2;</code>
   * @return Whether the hasMetadata field is set.
   */
  boolean hasHasMetadata();
  /**
   * <pre>
   * Whether this element has VE metadata set.
   * </pre>
   *
   * <code>optional bool has_metadata = 2;</code>
   * @return The hasMetadata.
   */
  boolean getHasMetadata();

  /**
   * <pre>
   * The Java package name to use for the generated VE metadata file.
   * </pre>
   *
   * <code>optional string java_package = 3;</code>
   * @return Whether the javaPackage field is set.
   */
  boolean hasJavaPackage();
  /**
   * <pre>
   * The Java package name to use for the generated VE metadata file.
   * </pre>
   *
   * <code>optional string java_package = 3;</code>
   * @return The javaPackage.
   */
  java.lang.String getJavaPackage();
  /**
   * <pre>
   * The Java package name to use for the generated VE metadata file.
   * </pre>
   *
   * <code>optional string java_package = 3;</code>
   * @return The bytes for javaPackage.
   */
  com.google.protobuf.ByteString
      getJavaPackageBytes();

  /**
   * <pre>
   * The JS package name to use to reference the generated VE metadata file.
   * </pre>
   *
   * <code>optional string js_package = 5;</code>
   * @return Whether the jsPackage field is set.
   */
  boolean hasJsPackage();
  /**
   * <pre>
   * The JS package name to use to reference the generated VE metadata file.
   * </pre>
   *
   * <code>optional string js_package = 5;</code>
   * @return The jsPackage.
   */
  java.lang.String getJsPackage();
  /**
   * <pre>
   * The JS package name to use to reference the generated VE metadata file.
   * </pre>
   *
   * <code>optional string js_package = 5;</code>
   * @return The bytes for jsPackage.
   */
  com.google.protobuf.ByteString
      getJsPackageBytes();

  /**
   * <pre>
   * The class name to use for the generated VE metadata file.
   * </pre>
   *
   * <code>optional string class_name = 4;</code>
   * @return Whether the className field is set.
   */
  boolean hasClassName();
  /**
   * <pre>
   * The class name to use for the generated VE metadata file.
   * </pre>
   *
   * <code>optional string class_name = 4;</code>
   * @return The className.
   */
  java.lang.String getClassName();
  /**
   * <pre>
   * The class name to use for the generated VE metadata file.
   * </pre>
   *
   * <code>optional string class_name = 4;</code>
   * @return The bytes for className.
   */
  com.google.protobuf.ByteString
      getClassNameBytes();
}
