// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: src/main/protobuf/annotated_logging_config.proto
// Protobuf Java Version: 4.28.2

package com.google.template.soy.logging;

/**
 * <pre>
 * A Soy-internal version of LoggableElement that contains additional Soy-only
 * details.
 * </pre>
 *
 * Protobuf type {@code soy.AnnotatedLoggableElement}
 */
public final class AnnotatedLoggableElement extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:soy.AnnotatedLoggableElement)
    AnnotatedLoggableElementOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 28,
      /* patch= */ 2,
      /* suffix= */ "",
      AnnotatedLoggableElement.class.getName());
  }
  // Use AnnotatedLoggableElement.newBuilder() to construct.
  private AnnotatedLoggableElement(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private AnnotatedLoggableElement() {
    javaPackage_ = "";
    jsPackage_ = "";
    className_ = "";
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.google.template.soy.logging.AnnotatedLoggingConfigOuterClass.internal_static_soy_AnnotatedLoggableElement_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.google.template.soy.logging.AnnotatedLoggingConfigOuterClass.internal_static_soy_AnnotatedLoggableElement_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.google.template.soy.logging.AnnotatedLoggableElement.class, com.google.template.soy.logging.AnnotatedLoggableElement.Builder.class);
  }

  private int bitField0_;
  public static final int ELEMENT_FIELD_NUMBER = 1;
  private com.google.template.soy.logging.LoggableElement element_;
  /**
   * <pre>
   * The actual LoggableElement.
   * </pre>
   *
   * <code>optional .soy.LoggableElement element = 1;</code>
   * @return Whether the element field is set.
   */
  @java.lang.Override
  public boolean hasElement() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <pre>
   * The actual LoggableElement.
   * </pre>
   *
   * <code>optional .soy.LoggableElement element = 1;</code>
   * @return The element.
   */
  @java.lang.Override
  public com.google.template.soy.logging.LoggableElement getElement() {
    return element_ == null ? com.google.template.soy.logging.LoggableElement.getDefaultInstance() : element_;
  }
  /**
   * <pre>
   * The actual LoggableElement.
   * </pre>
   *
   * <code>optional .soy.LoggableElement element = 1;</code>
   */
  @java.lang.Override
  public com.google.template.soy.logging.LoggableElementOrBuilder getElementOrBuilder() {
    return element_ == null ? com.google.template.soy.logging.LoggableElement.getDefaultInstance() : element_;
  }

  public static final int HAS_METADATA_FIELD_NUMBER = 2;
  private boolean hasMetadata_ = false;
  /**
   * <pre>
   * Whether this element has VE metadata set.
   * </pre>
   *
   * <code>optional bool has_metadata = 2;</code>
   * @return Whether the hasMetadata field is set.
   */
  @java.lang.Override
  public boolean hasHasMetadata() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <pre>
   * Whether this element has VE metadata set.
   * </pre>
   *
   * <code>optional bool has_metadata = 2;</code>
   * @return The hasMetadata.
   */
  @java.lang.Override
  public boolean getHasMetadata() {
    return hasMetadata_;
  }

  public static final int JAVA_PACKAGE_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private volatile java.lang.Object javaPackage_ = "";
  /**
   * <pre>
   * The Java package name to use for the generated VE metadata file.
   * </pre>
   *
   * <code>optional string java_package = 3;</code>
   * @return Whether the javaPackage field is set.
   */
  @java.lang.Override
  public boolean hasJavaPackage() {
    return ((bitField0_ & 0x00000004) != 0);
  }
  /**
   * <pre>
   * The Java package name to use for the generated VE metadata file.
   * </pre>
   *
   * <code>optional string java_package = 3;</code>
   * @return The javaPackage.
   */
  @java.lang.Override
  public java.lang.String getJavaPackage() {
    java.lang.Object ref = javaPackage_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (bs.isValidUtf8()) {
        javaPackage_ = s;
      }
      return s;
    }
  }
  /**
   * <pre>
   * The Java package name to use for the generated VE metadata file.
   * </pre>
   *
   * <code>optional string java_package = 3;</code>
   * @return The bytes for javaPackage.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getJavaPackageBytes() {
    java.lang.Object ref = javaPackage_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      javaPackage_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int JS_PACKAGE_FIELD_NUMBER = 5;
  @SuppressWarnings("serial")
  private volatile java.lang.Object jsPackage_ = "";
  /**
   * <pre>
   * The JS package name to use to reference the generated VE metadata file.
   * </pre>
   *
   * <code>optional string js_package = 5;</code>
   * @return Whether the jsPackage field is set.
   */
  @java.lang.Override
  public boolean hasJsPackage() {
    return ((bitField0_ & 0x00000008) != 0);
  }
  /**
   * <pre>
   * The JS package name to use to reference the generated VE metadata file.
   * </pre>
   *
   * <code>optional string js_package = 5;</code>
   * @return The jsPackage.
   */
  @java.lang.Override
  public java.lang.String getJsPackage() {
    java.lang.Object ref = jsPackage_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (bs.isValidUtf8()) {
        jsPackage_ = s;
      }
      return s;
    }
  }
  /**
   * <pre>
   * The JS package name to use to reference the generated VE metadata file.
   * </pre>
   *
   * <code>optional string js_package = 5;</code>
   * @return The bytes for jsPackage.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getJsPackageBytes() {
    java.lang.Object ref = jsPackage_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      jsPackage_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CLASS_NAME_FIELD_NUMBER = 4;
  @SuppressWarnings("serial")
  private volatile java.lang.Object className_ = "";
  /**
   * <pre>
   * The class name to use for the generated VE metadata file.
   * </pre>
   *
   * <code>optional string class_name = 4;</code>
   * @return Whether the className field is set.
   */
  @java.lang.Override
  public boolean hasClassName() {
    return ((bitField0_ & 0x00000010) != 0);
  }
  /**
   * <pre>
   * The class name to use for the generated VE metadata file.
   * </pre>
   *
   * <code>optional string class_name = 4;</code>
   * @return The className.
   */
  @java.lang.Override
  public java.lang.String getClassName() {
    java.lang.Object ref = className_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (bs.isValidUtf8()) {
        className_ = s;
      }
      return s;
    }
  }
  /**
   * <pre>
   * The class name to use for the generated VE metadata file.
   * </pre>
   *
   * <code>optional string class_name = 4;</code>
   * @return The bytes for className.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getClassNameBytes() {
    java.lang.Object ref = className_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      className_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    if (hasElement()) {
      if (!getElement().isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
    }
    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(1, getElement());
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      output.writeBool(2, hasMetadata_);
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 3, javaPackage_);
    }
    if (((bitField0_ & 0x00000010) != 0)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 4, className_);
    }
    if (((bitField0_ & 0x00000008) != 0)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 5, jsPackage_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getElement());
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(2, hasMetadata_);
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(3, javaPackage_);
    }
    if (((bitField0_ & 0x00000010) != 0)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(4, className_);
    }
    if (((bitField0_ & 0x00000008) != 0)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(5, jsPackage_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.google.template.soy.logging.AnnotatedLoggableElement)) {
      return super.equals(obj);
    }
    com.google.template.soy.logging.AnnotatedLoggableElement other = (com.google.template.soy.logging.AnnotatedLoggableElement) obj;

    if (hasElement() != other.hasElement()) return false;
    if (hasElement()) {
      if (!getElement()
          .equals(other.getElement())) return false;
    }
    if (hasHasMetadata() != other.hasHasMetadata()) return false;
    if (hasHasMetadata()) {
      if (getHasMetadata()
          != other.getHasMetadata()) return false;
    }
    if (hasJavaPackage() != other.hasJavaPackage()) return false;
    if (hasJavaPackage()) {
      if (!getJavaPackage()
          .equals(other.getJavaPackage())) return false;
    }
    if (hasJsPackage() != other.hasJsPackage()) return false;
    if (hasJsPackage()) {
      if (!getJsPackage()
          .equals(other.getJsPackage())) return false;
    }
    if (hasClassName() != other.hasClassName()) return false;
    if (hasClassName()) {
      if (!getClassName()
          .equals(other.getClassName())) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasElement()) {
      hash = (37 * hash) + ELEMENT_FIELD_NUMBER;
      hash = (53 * hash) + getElement().hashCode();
    }
    if (hasHasMetadata()) {
      hash = (37 * hash) + HAS_METADATA_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getHasMetadata());
    }
    if (hasJavaPackage()) {
      hash = (37 * hash) + JAVA_PACKAGE_FIELD_NUMBER;
      hash = (53 * hash) + getJavaPackage().hashCode();
    }
    if (hasJsPackage()) {
      hash = (37 * hash) + JS_PACKAGE_FIELD_NUMBER;
      hash = (53 * hash) + getJsPackage().hashCode();
    }
    if (hasClassName()) {
      hash = (37 * hash) + CLASS_NAME_FIELD_NUMBER;
      hash = (53 * hash) + getClassName().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.google.template.soy.logging.AnnotatedLoggableElement parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.google.template.soy.logging.AnnotatedLoggableElement parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.google.template.soy.logging.AnnotatedLoggableElement parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.google.template.soy.logging.AnnotatedLoggableElement parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.google.template.soy.logging.AnnotatedLoggableElement parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.google.template.soy.logging.AnnotatedLoggableElement parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.google.template.soy.logging.AnnotatedLoggableElement parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.google.template.soy.logging.AnnotatedLoggableElement parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.google.template.soy.logging.AnnotatedLoggableElement parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.google.template.soy.logging.AnnotatedLoggableElement parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.google.template.soy.logging.AnnotatedLoggableElement parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.google.template.soy.logging.AnnotatedLoggableElement parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.google.template.soy.logging.AnnotatedLoggableElement prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * A Soy-internal version of LoggableElement that contains additional Soy-only
   * details.
   * </pre>
   *
   * Protobuf type {@code soy.AnnotatedLoggableElement}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:soy.AnnotatedLoggableElement)
      com.google.template.soy.logging.AnnotatedLoggableElementOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.google.template.soy.logging.AnnotatedLoggingConfigOuterClass.internal_static_soy_AnnotatedLoggableElement_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.google.template.soy.logging.AnnotatedLoggingConfigOuterClass.internal_static_soy_AnnotatedLoggableElement_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.google.template.soy.logging.AnnotatedLoggableElement.class, com.google.template.soy.logging.AnnotatedLoggableElement.Builder.class);
    }

    // Construct using com.google.template.soy.logging.AnnotatedLoggableElement.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage
              .alwaysUseFieldBuilders) {
        getElementFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      element_ = null;
      if (elementBuilder_ != null) {
        elementBuilder_.dispose();
        elementBuilder_ = null;
      }
      hasMetadata_ = false;
      javaPackage_ = "";
      jsPackage_ = "";
      className_ = "";
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.google.template.soy.logging.AnnotatedLoggingConfigOuterClass.internal_static_soy_AnnotatedLoggableElement_descriptor;
    }

    @java.lang.Override
    public com.google.template.soy.logging.AnnotatedLoggableElement getDefaultInstanceForType() {
      return com.google.template.soy.logging.AnnotatedLoggableElement.getDefaultInstance();
    }

    @java.lang.Override
    public com.google.template.soy.logging.AnnotatedLoggableElement build() {
      com.google.template.soy.logging.AnnotatedLoggableElement result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.google.template.soy.logging.AnnotatedLoggableElement buildPartial() {
      com.google.template.soy.logging.AnnotatedLoggableElement result = new com.google.template.soy.logging.AnnotatedLoggableElement(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.google.template.soy.logging.AnnotatedLoggableElement result) {
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.element_ = elementBuilder_ == null
            ? element_
            : elementBuilder_.build();
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.hasMetadata_ = hasMetadata_;
        to_bitField0_ |= 0x00000002;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.javaPackage_ = javaPackage_;
        to_bitField0_ |= 0x00000004;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.jsPackage_ = jsPackage_;
        to_bitField0_ |= 0x00000008;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.className_ = className_;
        to_bitField0_ |= 0x00000010;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.google.template.soy.logging.AnnotatedLoggableElement) {
        return mergeFrom((com.google.template.soy.logging.AnnotatedLoggableElement)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.google.template.soy.logging.AnnotatedLoggableElement other) {
      if (other == com.google.template.soy.logging.AnnotatedLoggableElement.getDefaultInstance()) return this;
      if (other.hasElement()) {
        mergeElement(other.getElement());
      }
      if (other.hasHasMetadata()) {
        setHasMetadata(other.getHasMetadata());
      }
      if (other.hasJavaPackage()) {
        javaPackage_ = other.javaPackage_;
        bitField0_ |= 0x00000004;
        onChanged();
      }
      if (other.hasJsPackage()) {
        jsPackage_ = other.jsPackage_;
        bitField0_ |= 0x00000008;
        onChanged();
      }
      if (other.hasClassName()) {
        className_ = other.className_;
        bitField0_ |= 0x00000010;
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      if (hasElement()) {
        if (!getElement().isInitialized()) {
          return false;
        }
      }
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              input.readMessage(
                  getElementFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 16: {
              hasMetadata_ = input.readBool();
              bitField0_ |= 0x00000002;
              break;
            } // case 16
            case 26: {
              javaPackage_ = input.readBytes();
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            case 34: {
              className_ = input.readBytes();
              bitField0_ |= 0x00000010;
              break;
            } // case 34
            case 42: {
              jsPackage_ = input.readBytes();
              bitField0_ |= 0x00000008;
              break;
            } // case 42
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private com.google.template.soy.logging.LoggableElement element_;
    private com.google.protobuf.SingleFieldBuilder<
        com.google.template.soy.logging.LoggableElement, com.google.template.soy.logging.LoggableElement.Builder, com.google.template.soy.logging.LoggableElementOrBuilder> elementBuilder_;
    /**
     * <pre>
     * The actual LoggableElement.
     * </pre>
     *
     * <code>optional .soy.LoggableElement element = 1;</code>
     * @return Whether the element field is set.
     */
    public boolean hasElement() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <pre>
     * The actual LoggableElement.
     * </pre>
     *
     * <code>optional .soy.LoggableElement element = 1;</code>
     * @return The element.
     */
    public com.google.template.soy.logging.LoggableElement getElement() {
      if (elementBuilder_ == null) {
        return element_ == null ? com.google.template.soy.logging.LoggableElement.getDefaultInstance() : element_;
      } else {
        return elementBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * The actual LoggableElement.
     * </pre>
     *
     * <code>optional .soy.LoggableElement element = 1;</code>
     */
    public Builder setElement(com.google.template.soy.logging.LoggableElement value) {
      if (elementBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        element_ = value;
      } else {
        elementBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The actual LoggableElement.
     * </pre>
     *
     * <code>optional .soy.LoggableElement element = 1;</code>
     */
    public Builder setElement(
        com.google.template.soy.logging.LoggableElement.Builder builderForValue) {
      if (elementBuilder_ == null) {
        element_ = builderForValue.build();
      } else {
        elementBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The actual LoggableElement.
     * </pre>
     *
     * <code>optional .soy.LoggableElement element = 1;</code>
     */
    public Builder mergeElement(com.google.template.soy.logging.LoggableElement value) {
      if (elementBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0) &&
          element_ != null &&
          element_ != com.google.template.soy.logging.LoggableElement.getDefaultInstance()) {
          getElementBuilder().mergeFrom(value);
        } else {
          element_ = value;
        }
      } else {
        elementBuilder_.mergeFrom(value);
      }
      if (element_ != null) {
        bitField0_ |= 0x00000001;
        onChanged();
      }
      return this;
    }
    /**
     * <pre>
     * The actual LoggableElement.
     * </pre>
     *
     * <code>optional .soy.LoggableElement element = 1;</code>
     */
    public Builder clearElement() {
      bitField0_ = (bitField0_ & ~0x00000001);
      element_ = null;
      if (elementBuilder_ != null) {
        elementBuilder_.dispose();
        elementBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The actual LoggableElement.
     * </pre>
     *
     * <code>optional .soy.LoggableElement element = 1;</code>
     */
    public com.google.template.soy.logging.LoggableElement.Builder getElementBuilder() {
      bitField0_ |= 0x00000001;
      onChanged();
      return getElementFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * The actual LoggableElement.
     * </pre>
     *
     * <code>optional .soy.LoggableElement element = 1;</code>
     */
    public com.google.template.soy.logging.LoggableElementOrBuilder getElementOrBuilder() {
      if (elementBuilder_ != null) {
        return elementBuilder_.getMessageOrBuilder();
      } else {
        return element_ == null ?
            com.google.template.soy.logging.LoggableElement.getDefaultInstance() : element_;
      }
    }
    /**
     * <pre>
     * The actual LoggableElement.
     * </pre>
     *
     * <code>optional .soy.LoggableElement element = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        com.google.template.soy.logging.LoggableElement, com.google.template.soy.logging.LoggableElement.Builder, com.google.template.soy.logging.LoggableElementOrBuilder> 
        getElementFieldBuilder() {
      if (elementBuilder_ == null) {
        elementBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            com.google.template.soy.logging.LoggableElement, com.google.template.soy.logging.LoggableElement.Builder, com.google.template.soy.logging.LoggableElementOrBuilder>(
                getElement(),
                getParentForChildren(),
                isClean());
        element_ = null;
      }
      return elementBuilder_;
    }

    private boolean hasMetadata_ ;
    /**
     * <pre>
     * Whether this element has VE metadata set.
     * </pre>
     *
     * <code>optional bool has_metadata = 2;</code>
     * @return Whether the hasMetadata field is set.
     */
    @java.lang.Override
    public boolean hasHasMetadata() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <pre>
     * Whether this element has VE metadata set.
     * </pre>
     *
     * <code>optional bool has_metadata = 2;</code>
     * @return The hasMetadata.
     */
    @java.lang.Override
    public boolean getHasMetadata() {
      return hasMetadata_;
    }
    /**
     * <pre>
     * Whether this element has VE metadata set.
     * </pre>
     *
     * <code>optional bool has_metadata = 2;</code>
     * @param value The hasMetadata to set.
     * @return This builder for chaining.
     */
    public Builder setHasMetadata(boolean value) {

      hasMetadata_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Whether this element has VE metadata set.
     * </pre>
     *
     * <code>optional bool has_metadata = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearHasMetadata() {
      bitField0_ = (bitField0_ & ~0x00000002);
      hasMetadata_ = false;
      onChanged();
      return this;
    }

    private java.lang.Object javaPackage_ = "";
    /**
     * <pre>
     * The Java package name to use for the generated VE metadata file.
     * </pre>
     *
     * <code>optional string java_package = 3;</code>
     * @return Whether the javaPackage field is set.
     */
    public boolean hasJavaPackage() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <pre>
     * The Java package name to use for the generated VE metadata file.
     * </pre>
     *
     * <code>optional string java_package = 3;</code>
     * @return The javaPackage.
     */
    public java.lang.String getJavaPackage() {
      java.lang.Object ref = javaPackage_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          javaPackage_ = s;
        }
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * The Java package name to use for the generated VE metadata file.
     * </pre>
     *
     * <code>optional string java_package = 3;</code>
     * @return The bytes for javaPackage.
     */
    public com.google.protobuf.ByteString
        getJavaPackageBytes() {
      java.lang.Object ref = javaPackage_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        javaPackage_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * The Java package name to use for the generated VE metadata file.
     * </pre>
     *
     * <code>optional string java_package = 3;</code>
     * @param value The javaPackage to set.
     * @return This builder for chaining.
     */
    public Builder setJavaPackage(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      javaPackage_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The Java package name to use for the generated VE metadata file.
     * </pre>
     *
     * <code>optional string java_package = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearJavaPackage() {
      javaPackage_ = getDefaultInstance().getJavaPackage();
      bitField0_ = (bitField0_ & ~0x00000004);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The Java package name to use for the generated VE metadata file.
     * </pre>
     *
     * <code>optional string java_package = 3;</code>
     * @param value The bytes for javaPackage to set.
     * @return This builder for chaining.
     */
    public Builder setJavaPackageBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      javaPackage_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }

    private java.lang.Object jsPackage_ = "";
    /**
     * <pre>
     * The JS package name to use to reference the generated VE metadata file.
     * </pre>
     *
     * <code>optional string js_package = 5;</code>
     * @return Whether the jsPackage field is set.
     */
    public boolean hasJsPackage() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <pre>
     * The JS package name to use to reference the generated VE metadata file.
     * </pre>
     *
     * <code>optional string js_package = 5;</code>
     * @return The jsPackage.
     */
    public java.lang.String getJsPackage() {
      java.lang.Object ref = jsPackage_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          jsPackage_ = s;
        }
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * The JS package name to use to reference the generated VE metadata file.
     * </pre>
     *
     * <code>optional string js_package = 5;</code>
     * @return The bytes for jsPackage.
     */
    public com.google.protobuf.ByteString
        getJsPackageBytes() {
      java.lang.Object ref = jsPackage_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        jsPackage_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * The JS package name to use to reference the generated VE metadata file.
     * </pre>
     *
     * <code>optional string js_package = 5;</code>
     * @param value The jsPackage to set.
     * @return This builder for chaining.
     */
    public Builder setJsPackage(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      jsPackage_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The JS package name to use to reference the generated VE metadata file.
     * </pre>
     *
     * <code>optional string js_package = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearJsPackage() {
      jsPackage_ = getDefaultInstance().getJsPackage();
      bitField0_ = (bitField0_ & ~0x00000008);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The JS package name to use to reference the generated VE metadata file.
     * </pre>
     *
     * <code>optional string js_package = 5;</code>
     * @param value The bytes for jsPackage to set.
     * @return This builder for chaining.
     */
    public Builder setJsPackageBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      jsPackage_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }

    private java.lang.Object className_ = "";
    /**
     * <pre>
     * The class name to use for the generated VE metadata file.
     * </pre>
     *
     * <code>optional string class_name = 4;</code>
     * @return Whether the className field is set.
     */
    public boolean hasClassName() {
      return ((bitField0_ & 0x00000010) != 0);
    }
    /**
     * <pre>
     * The class name to use for the generated VE metadata file.
     * </pre>
     *
     * <code>optional string class_name = 4;</code>
     * @return The className.
     */
    public java.lang.String getClassName() {
      java.lang.Object ref = className_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          className_ = s;
        }
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * The class name to use for the generated VE metadata file.
     * </pre>
     *
     * <code>optional string class_name = 4;</code>
     * @return The bytes for className.
     */
    public com.google.protobuf.ByteString
        getClassNameBytes() {
      java.lang.Object ref = className_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        className_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * The class name to use for the generated VE metadata file.
     * </pre>
     *
     * <code>optional string class_name = 4;</code>
     * @param value The className to set.
     * @return This builder for chaining.
     */
    public Builder setClassName(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      className_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The class name to use for the generated VE metadata file.
     * </pre>
     *
     * <code>optional string class_name = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearClassName() {
      className_ = getDefaultInstance().getClassName();
      bitField0_ = (bitField0_ & ~0x00000010);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The class name to use for the generated VE metadata file.
     * </pre>
     *
     * <code>optional string class_name = 4;</code>
     * @param value The bytes for className to set.
     * @return This builder for chaining.
     */
    public Builder setClassNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      className_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:soy.AnnotatedLoggableElement)
  }

  // @@protoc_insertion_point(class_scope:soy.AnnotatedLoggableElement)
  private static final com.google.template.soy.logging.AnnotatedLoggableElement DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.google.template.soy.logging.AnnotatedLoggableElement();
  }

  public static com.google.template.soy.logging.AnnotatedLoggableElement getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<AnnotatedLoggableElement>
      PARSER = new com.google.protobuf.AbstractParser<AnnotatedLoggableElement>() {
    @java.lang.Override
    public AnnotatedLoggableElement parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<AnnotatedLoggableElement> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<AnnotatedLoggableElement> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.template.soy.logging.AnnotatedLoggableElement getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

