// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: src/main/protobuf/annotated_logging_config.proto
// Protobuf Java Version: 4.28.2

package com.google.template.soy.logging;

public final class AnnotatedLoggingConfigOuterClass {
  private AnnotatedLoggingConfigOuterClass() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 28,
      /* patch= */ 2,
      /* suffix= */ "",
      AnnotatedLoggingConfigOuterClass.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_soy_AnnotatedLoggingConfig_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_soy_AnnotatedLoggingConfig_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_soy_AnnotatedLoggableElement_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_soy_AnnotatedLoggableElement_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n0src/main/protobuf/annotated_logging_co" +
      "nfig.proto\022\003soy\032&src/main/protobuf/loggi" +
      "ng_config.proto\"H\n\026AnnotatedLoggingConfi" +
      "g\022.\n\007element\030\001 \003(\0132\035.soy.AnnotatedLoggab" +
      "leElement\"\225\001\n\030AnnotatedLoggableElement\022%" +
      "\n\007element\030\001 \001(\0132\024.soy.LoggableElement\022\024\n" +
      "\014has_metadata\030\002 \001(\010\022\024\n\014java_package\030\003 \001(" +
      "\t\022\022\n\njs_package\030\005 \001(\t\022\022\n\nclass_name\030\004 \001(" +
      "\tB#\n\037com.google.template.soy.loggingP\001"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.template.soy.logging.LoggingConfigOuterClass.getDescriptor(),
        });
    internal_static_soy_AnnotatedLoggingConfig_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_soy_AnnotatedLoggingConfig_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_soy_AnnotatedLoggingConfig_descriptor,
        new java.lang.String[] { "Element", });
    internal_static_soy_AnnotatedLoggableElement_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_soy_AnnotatedLoggableElement_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_soy_AnnotatedLoggableElement_descriptor,
        new java.lang.String[] { "Element", "HasMetadata", "JavaPackage", "JsPackage", "ClassName", });
    descriptor.resolveAllFeaturesImmutable();
    com.google.template.soy.logging.LoggingConfigOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
