// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: src/main/protobuf/logging_config.proto
// Protobuf Java Version: 4.28.2

package com.google.template.soy.logging;

public interface LoggingConfigOrBuilder extends
    // @@protoc_insertion_point(interface_extends:soy.LoggingConfig)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * All the logging elements that are configured for the current compilation
   * unit.
   * </pre>
   *
   * <code>repeated .soy.LoggableElement element = 1;</code>
   */
  java.util.List<com.google.template.soy.logging.LoggableElement> 
      getElementList();
  /**
   * <pre>
   * All the logging elements that are configured for the current compilation
   * unit.
   * </pre>
   *
   * <code>repeated .soy.LoggableElement element = 1;</code>
   */
  com.google.template.soy.logging.LoggableElement getElement(int index);
  /**
   * <pre>
   * All the logging elements that are configured for the current compilation
   * unit.
   * </pre>
   *
   * <code>repeated .soy.LoggableElement element = 1;</code>
   */
  int getElementCount();
  /**
   * <pre>
   * All the logging elements that are configured for the current compilation
   * unit.
   * </pre>
   *
   * <code>repeated .soy.LoggableElement element = 1;</code>
   */
  java.util.List<? extends com.google.template.soy.logging.LoggableElementOrBuilder> 
      getElementOrBuilderList();
  /**
   * <pre>
   * All the logging elements that are configured for the current compilation
   * unit.
   * </pre>
   *
   * <code>repeated .soy.LoggableElement element = 1;</code>
   */
  com.google.template.soy.logging.LoggableElementOrBuilder getElementOrBuilder(
      int index);
}
