// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: src/main/protobuf/ve_metadata.proto
// Protobuf Java Version: 4.28.2

package com.google.template.soy.logging;

public interface LoggableElementMetadataOrBuilder extends
    // @@protoc_insertion_point(interface_extends:soy.LoggableElementMetadata)
    com.google.protobuf.GeneratedMessage.
        ExtendableMessageOrBuilder<LoggableElementMetadata> {
}
