// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: src/main/protobuf/logging_config.proto
// Protobuf Java Version: 4.28.2

package com.google.template.soy.logging;

public final class LoggingConfigOuterClass {
  private LoggingConfigOuterClass() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 28,
      /* patch= */ 2,
      /* suffix= */ "",
      LoggingConfigOuterClass.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_soy_LoggingConfig_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_soy_LoggingConfig_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_soy_LoggableElement_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_soy_LoggableElement_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n&src/main/protobuf/logging_config.proto" +
      "\022\003soy\032#src/main/protobuf/ve_metadata.pro" +
      "to\"6\n\rLoggingConfig\022%\n\007element\030\001 \003(\0132\024.s" +
      "oy.LoggableElement\"o\n\017LoggableElement\022\014\n" +
      "\004name\030\001 \001(\t\022\n\n\002id\030\002 \001(\003\022\022\n\nproto_type\030\003 " +
      "\001(\t\022.\n\010metadata\030\004 \001(\0132\034.soy.LoggableElem" +
      "entMetadataB#\n\037com.google.template.soy.l" +
      "oggingP\001"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.template.soy.logging.VeMetadata.getDescriptor(),
        });
    internal_static_soy_LoggingConfig_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_soy_LoggingConfig_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_soy_LoggingConfig_descriptor,
        new java.lang.String[] { "Element", });
    internal_static_soy_LoggableElement_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_soy_LoggableElement_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_soy_LoggableElement_descriptor,
        new java.lang.String[] { "Name", "Id", "ProtoType", "Metadata", });
    descriptor.resolveAllFeaturesImmutable();
    com.google.template.soy.logging.VeMetadata.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
