// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: src/main/protobuf/ve_metadata.proto
// Protobuf Java Version: 4.28.2

package com.google.template.soy.logging;

/**
 * <pre>
 * Additional metadata to be included with a loggable element. Extend this and
 * set the metadata in your logging config. Note that metadata will be
 * serialized in JS and sent to the client, so copious metadata could bloat JS
 * size. To keep JS code size down, we recommend using smart defaults for
 * metadata (so metadata only has to be sent to the client if the value is
 * different than the default) and only setting the metadata on a VE if that
 * metadata is different from the default.
 * </pre>
 *
 * Protobuf type {@code soy.LoggableElementMetadata}
 */
public final class LoggableElementMetadata extends
    com.google.protobuf.GeneratedMessage.ExtendableMessage<
      LoggableElementMetadata> implements
    // @@protoc_insertion_point(message_implements:soy.LoggableElementMetadata)
    LoggableElementMetadataOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 28,
      /* patch= */ 2,
      /* suffix= */ "",
      LoggableElementMetadata.class.getName());
  }
  // Use LoggableElementMetadata.newBuilder() to construct.
  private LoggableElementMetadata(com.google.protobuf.GeneratedMessage.ExtendableBuilder<com.google.template.soy.logging.LoggableElementMetadata, ?> builder) {
    super(builder);
  }
  private LoggableElementMetadata() {
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.google.template.soy.logging.VeMetadata.internal_static_soy_LoggableElementMetadata_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.google.template.soy.logging.VeMetadata.internal_static_soy_LoggableElementMetadata_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.google.template.soy.logging.LoggableElementMetadata.class, com.google.template.soy.logging.LoggableElementMetadata.Builder.class);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    if (!extensionsAreInitialized()) {
      memoizedIsInitialized = 0;
      return false;
    }
    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    com.google.protobuf.GeneratedMessage
      .ExtendableMessage.ExtensionSerializer
        extensionWriter = newExtensionSerializer();
    extensionWriter.writeUntil(536870912, output);
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    size += extensionsSerializedSize();
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.google.template.soy.logging.LoggableElementMetadata)) {
      return super.equals(obj);
    }
    com.google.template.soy.logging.LoggableElementMetadata other = (com.google.template.soy.logging.LoggableElementMetadata) obj;

    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    if (!getExtensionFields().equals(other.getExtensionFields()))
      return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = hashFields(hash, getExtensionFields());
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.google.template.soy.logging.LoggableElementMetadata parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.google.template.soy.logging.LoggableElementMetadata parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.google.template.soy.logging.LoggableElementMetadata parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.google.template.soy.logging.LoggableElementMetadata parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.google.template.soy.logging.LoggableElementMetadata parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.google.template.soy.logging.LoggableElementMetadata parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.google.template.soy.logging.LoggableElementMetadata parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.google.template.soy.logging.LoggableElementMetadata parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.google.template.soy.logging.LoggableElementMetadata parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.google.template.soy.logging.LoggableElementMetadata parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.google.template.soy.logging.LoggableElementMetadata parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.google.template.soy.logging.LoggableElementMetadata parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.google.template.soy.logging.LoggableElementMetadata prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * Additional metadata to be included with a loggable element. Extend this and
   * set the metadata in your logging config. Note that metadata will be
   * serialized in JS and sent to the client, so copious metadata could bloat JS
   * size. To keep JS code size down, we recommend using smart defaults for
   * metadata (so metadata only has to be sent to the client if the value is
   * different than the default) and only setting the metadata on a VE if that
   * metadata is different from the default.
   * </pre>
   *
   * Protobuf type {@code soy.LoggableElementMetadata}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.ExtendableBuilder<
        com.google.template.soy.logging.LoggableElementMetadata, Builder> implements
      // @@protoc_insertion_point(builder_implements:soy.LoggableElementMetadata)
      com.google.template.soy.logging.LoggableElementMetadataOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.google.template.soy.logging.VeMetadata.internal_static_soy_LoggableElementMetadata_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.google.template.soy.logging.VeMetadata.internal_static_soy_LoggableElementMetadata_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.google.template.soy.logging.LoggableElementMetadata.class, com.google.template.soy.logging.LoggableElementMetadata.Builder.class);
    }

    // Construct using com.google.template.soy.logging.LoggableElementMetadata.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.google.template.soy.logging.VeMetadata.internal_static_soy_LoggableElementMetadata_descriptor;
    }

    @java.lang.Override
    public com.google.template.soy.logging.LoggableElementMetadata getDefaultInstanceForType() {
      return com.google.template.soy.logging.LoggableElementMetadata.getDefaultInstance();
    }

    @java.lang.Override
    public com.google.template.soy.logging.LoggableElementMetadata build() {
      com.google.template.soy.logging.LoggableElementMetadata result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.google.template.soy.logging.LoggableElementMetadata buildPartial() {
      com.google.template.soy.logging.LoggableElementMetadata result = new com.google.template.soy.logging.LoggableElementMetadata(this);
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.google.template.soy.logging.LoggableElementMetadata) {
        return mergeFrom((com.google.template.soy.logging.LoggableElementMetadata)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.google.template.soy.logging.LoggableElementMetadata other) {
      if (other == com.google.template.soy.logging.LoggableElementMetadata.getDefaultInstance()) return this;
      this.mergeExtensionFields(other);
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      if (!extensionsAreInitialized()) {
        return false;
      }
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }

    // @@protoc_insertion_point(builder_scope:soy.LoggableElementMetadata)
  }

  // @@protoc_insertion_point(class_scope:soy.LoggableElementMetadata)
  private static final com.google.template.soy.logging.LoggableElementMetadata DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.google.template.soy.logging.LoggableElementMetadata();
  }

  public static com.google.template.soy.logging.LoggableElementMetadata getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<LoggableElementMetadata>
      PARSER = new com.google.protobuf.AbstractParser<LoggableElementMetadata>() {
    @java.lang.Override
    public LoggableElementMetadata parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<LoggableElementMetadata> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<LoggableElementMetadata> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.template.soy.logging.LoggableElementMetadata getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

