// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: src/main/protobuf/logging_config.proto
// Protobuf Java Version: 4.28.2

package com.google.template.soy.logging;

public interface LoggableElementOrBuilder extends
    // @@protoc_insertion_point(interface_extends:soy.LoggableElement)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * The name specified by users in the soy file.  This should be a valid
   * soy identifier (it should match:
   * '[a-zA-Z_][a-zA-Z_0-9]*([.][a-zA-Z_][a-zA-Z_0-9]*)*' )
   * Must be unique.
   * </pre>
   *
   * <code>optional string name = 1;</code>
   * @return Whether the name field is set.
   */
  boolean hasName();
  /**
   * <pre>
   * The name specified by users in the soy file.  This should be a valid
   * soy identifier (it should match:
   * '[a-zA-Z_][a-zA-Z_0-9]*([.][a-zA-Z_][a-zA-Z_0-9]*)*' )
   * Must be unique.
   * </pre>
   *
   * <code>optional string name = 1;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <pre>
   * The name specified by users in the soy file.  This should be a valid
   * soy identifier (it should match:
   * '[a-zA-Z_][a-zA-Z_0-9]*([.][a-zA-Z_][a-zA-Z_0-9]*)*' )
   * Must be unique.
   * </pre>
   *
   * <code>optional string name = 1;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <pre>
   * The id that will be logged.  Must be unique.
   * </pre>
   *
   * <code>optional int64 id = 2;</code>
   * @return Whether the id field is set.
   */
  boolean hasId();
  /**
   * <pre>
   * The id that will be logged.  Must be unique.
   * </pre>
   *
   * <code>optional int64 id = 2;</code>
   * @return The id.
   */
  long getId();

  /**
   * <pre>
   * The fully qualified name of the protocol buffer that
   * will be used to specify metadata for the element.  Allowed to be the empty
   * string if there is no such proto.
   * </pre>
   *
   * <code>optional string proto_type = 3;</code>
   * @return Whether the protoType field is set.
   */
  boolean hasProtoType();
  /**
   * <pre>
   * The fully qualified name of the protocol buffer that
   * will be used to specify metadata for the element.  Allowed to be the empty
   * string if there is no such proto.
   * </pre>
   *
   * <code>optional string proto_type = 3;</code>
   * @return The protoType.
   */
  java.lang.String getProtoType();
  /**
   * <pre>
   * The fully qualified name of the protocol buffer that
   * will be used to specify metadata for the element.  Allowed to be the empty
   * string if there is no such proto.
   * </pre>
   *
   * <code>optional string proto_type = 3;</code>
   * @return The bytes for protoType.
   */
  com.google.protobuf.ByteString
      getProtoTypeBytes();

  /**
   * <pre>
   * Additional metadata to be included with this loggable element. Use this to
   * set compile-time constant VE metadata, that will be available from Soy
   * source code.
   * </pre>
   *
   * <code>optional .soy.LoggableElementMetadata metadata = 4;</code>
   * @return Whether the metadata field is set.
   */
  boolean hasMetadata();
  /**
   * <pre>
   * Additional metadata to be included with this loggable element. Use this to
   * set compile-time constant VE metadata, that will be available from Soy
   * source code.
   * </pre>
   *
   * <code>optional .soy.LoggableElementMetadata metadata = 4;</code>
   * @return The metadata.
   */
  com.google.template.soy.logging.LoggableElementMetadata getMetadata();
  /**
   * <pre>
   * Additional metadata to be included with this loggable element. Use this to
   * set compile-time constant VE metadata, that will be available from Soy
   * source code.
   * </pre>
   *
   * <code>optional .soy.LoggableElementMetadata metadata = 4;</code>
   */
  com.google.template.soy.logging.LoggableElementMetadataOrBuilder getMetadataOrBuilder();
}
