// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: src/main/protobuf/logging_config.proto
// Protobuf Java Version: 4.28.2

package com.google.template.soy.logging;

/**
 * <pre>
 * Defines a loggable element
 * </pre>
 *
 * Protobuf type {@code soy.LoggableElement}
 */
public final class LoggableElement extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:soy.LoggableElement)
    LoggableElementOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 28,
      /* patch= */ 2,
      /* suffix= */ "",
      LoggableElement.class.getName());
  }
  // Use LoggableElement.newBuilder() to construct.
  private LoggableElement(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private LoggableElement() {
    name_ = "";
    protoType_ = "";
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.google.template.soy.logging.LoggingConfigOuterClass.internal_static_soy_LoggableElement_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.google.template.soy.logging.LoggingConfigOuterClass.internal_static_soy_LoggableElement_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.google.template.soy.logging.LoggableElement.class, com.google.template.soy.logging.LoggableElement.Builder.class);
  }

  private int bitField0_;
  public static final int NAME_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object name_ = "";
  /**
   * <pre>
   * The name specified by users in the soy file.  This should be a valid
   * soy identifier (it should match:
   * '[a-zA-Z_][a-zA-Z_0-9]*([.][a-zA-Z_][a-zA-Z_0-9]*)*' )
   * Must be unique.
   * </pre>
   *
   * <code>optional string name = 1;</code>
   * @return Whether the name field is set.
   */
  @java.lang.Override
  public boolean hasName() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <pre>
   * The name specified by users in the soy file.  This should be a valid
   * soy identifier (it should match:
   * '[a-zA-Z_][a-zA-Z_0-9]*([.][a-zA-Z_][a-zA-Z_0-9]*)*' )
   * Must be unique.
   * </pre>
   *
   * <code>optional string name = 1;</code>
   * @return The name.
   */
  @java.lang.Override
  public java.lang.String getName() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (bs.isValidUtf8()) {
        name_ = s;
      }
      return s;
    }
  }
  /**
   * <pre>
   * The name specified by users in the soy file.  This should be a valid
   * soy identifier (it should match:
   * '[a-zA-Z_][a-zA-Z_0-9]*([.][a-zA-Z_][a-zA-Z_0-9]*)*' )
   * Must be unique.
   * </pre>
   *
   * <code>optional string name = 1;</code>
   * @return The bytes for name.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getNameBytes() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      name_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ID_FIELD_NUMBER = 2;
  private long id_ = 0L;
  /**
   * <pre>
   * The id that will be logged.  Must be unique.
   * </pre>
   *
   * <code>optional int64 id = 2;</code>
   * @return Whether the id field is set.
   */
  @java.lang.Override
  public boolean hasId() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <pre>
   * The id that will be logged.  Must be unique.
   * </pre>
   *
   * <code>optional int64 id = 2;</code>
   * @return The id.
   */
  @java.lang.Override
  public long getId() {
    return id_;
  }

  public static final int PROTO_TYPE_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private volatile java.lang.Object protoType_ = "";
  /**
   * <pre>
   * The fully qualified name of the protocol buffer that
   * will be used to specify metadata for the element.  Allowed to be the empty
   * string if there is no such proto.
   * </pre>
   *
   * <code>optional string proto_type = 3;</code>
   * @return Whether the protoType field is set.
   */
  @java.lang.Override
  public boolean hasProtoType() {
    return ((bitField0_ & 0x00000004) != 0);
  }
  /**
   * <pre>
   * The fully qualified name of the protocol buffer that
   * will be used to specify metadata for the element.  Allowed to be the empty
   * string if there is no such proto.
   * </pre>
   *
   * <code>optional string proto_type = 3;</code>
   * @return The protoType.
   */
  @java.lang.Override
  public java.lang.String getProtoType() {
    java.lang.Object ref = protoType_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (bs.isValidUtf8()) {
        protoType_ = s;
      }
      return s;
    }
  }
  /**
   * <pre>
   * The fully qualified name of the protocol buffer that
   * will be used to specify metadata for the element.  Allowed to be the empty
   * string if there is no such proto.
   * </pre>
   *
   * <code>optional string proto_type = 3;</code>
   * @return The bytes for protoType.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getProtoTypeBytes() {
    java.lang.Object ref = protoType_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      protoType_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int METADATA_FIELD_NUMBER = 4;
  private com.google.template.soy.logging.LoggableElementMetadata metadata_;
  /**
   * <pre>
   * Additional metadata to be included with this loggable element. Use this to
   * set compile-time constant VE metadata, that will be available from Soy
   * source code.
   * </pre>
   *
   * <code>optional .soy.LoggableElementMetadata metadata = 4;</code>
   * @return Whether the metadata field is set.
   */
  @java.lang.Override
  public boolean hasMetadata() {
    return ((bitField0_ & 0x00000008) != 0);
  }
  /**
   * <pre>
   * Additional metadata to be included with this loggable element. Use this to
   * set compile-time constant VE metadata, that will be available from Soy
   * source code.
   * </pre>
   *
   * <code>optional .soy.LoggableElementMetadata metadata = 4;</code>
   * @return The metadata.
   */
  @java.lang.Override
  public com.google.template.soy.logging.LoggableElementMetadata getMetadata() {
    return metadata_ == null ? com.google.template.soy.logging.LoggableElementMetadata.getDefaultInstance() : metadata_;
  }
  /**
   * <pre>
   * Additional metadata to be included with this loggable element. Use this to
   * set compile-time constant VE metadata, that will be available from Soy
   * source code.
   * </pre>
   *
   * <code>optional .soy.LoggableElementMetadata metadata = 4;</code>
   */
  @java.lang.Override
  public com.google.template.soy.logging.LoggableElementMetadataOrBuilder getMetadataOrBuilder() {
    return metadata_ == null ? com.google.template.soy.logging.LoggableElementMetadata.getDefaultInstance() : metadata_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    if (hasMetadata()) {
      if (!getMetadata().isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
    }
    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) != 0)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 1, name_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      output.writeInt64(2, id_);
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 3, protoType_);
    }
    if (((bitField0_ & 0x00000008) != 0)) {
      output.writeMessage(4, getMetadata());
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(1, name_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(2, id_);
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(3, protoType_);
    }
    if (((bitField0_ & 0x00000008) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, getMetadata());
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.google.template.soy.logging.LoggableElement)) {
      return super.equals(obj);
    }
    com.google.template.soy.logging.LoggableElement other = (com.google.template.soy.logging.LoggableElement) obj;

    if (hasName() != other.hasName()) return false;
    if (hasName()) {
      if (!getName()
          .equals(other.getName())) return false;
    }
    if (hasId() != other.hasId()) return false;
    if (hasId()) {
      if (getId()
          != other.getId()) return false;
    }
    if (hasProtoType() != other.hasProtoType()) return false;
    if (hasProtoType()) {
      if (!getProtoType()
          .equals(other.getProtoType())) return false;
    }
    if (hasMetadata() != other.hasMetadata()) return false;
    if (hasMetadata()) {
      if (!getMetadata()
          .equals(other.getMetadata())) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasName()) {
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
    }
    if (hasId()) {
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getId());
    }
    if (hasProtoType()) {
      hash = (37 * hash) + PROTO_TYPE_FIELD_NUMBER;
      hash = (53 * hash) + getProtoType().hashCode();
    }
    if (hasMetadata()) {
      hash = (37 * hash) + METADATA_FIELD_NUMBER;
      hash = (53 * hash) + getMetadata().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.google.template.soy.logging.LoggableElement parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.google.template.soy.logging.LoggableElement parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.google.template.soy.logging.LoggableElement parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.google.template.soy.logging.LoggableElement parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.google.template.soy.logging.LoggableElement parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.google.template.soy.logging.LoggableElement parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.google.template.soy.logging.LoggableElement parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.google.template.soy.logging.LoggableElement parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.google.template.soy.logging.LoggableElement parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.google.template.soy.logging.LoggableElement parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.google.template.soy.logging.LoggableElement parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.google.template.soy.logging.LoggableElement parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.google.template.soy.logging.LoggableElement prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * Defines a loggable element
   * </pre>
   *
   * Protobuf type {@code soy.LoggableElement}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:soy.LoggableElement)
      com.google.template.soy.logging.LoggableElementOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.google.template.soy.logging.LoggingConfigOuterClass.internal_static_soy_LoggableElement_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.google.template.soy.logging.LoggingConfigOuterClass.internal_static_soy_LoggableElement_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.google.template.soy.logging.LoggableElement.class, com.google.template.soy.logging.LoggableElement.Builder.class);
    }

    // Construct using com.google.template.soy.logging.LoggableElement.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage
              .alwaysUseFieldBuilders) {
        getMetadataFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      name_ = "";
      id_ = 0L;
      protoType_ = "";
      metadata_ = null;
      if (metadataBuilder_ != null) {
        metadataBuilder_.dispose();
        metadataBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.google.template.soy.logging.LoggingConfigOuterClass.internal_static_soy_LoggableElement_descriptor;
    }

    @java.lang.Override
    public com.google.template.soy.logging.LoggableElement getDefaultInstanceForType() {
      return com.google.template.soy.logging.LoggableElement.getDefaultInstance();
    }

    @java.lang.Override
    public com.google.template.soy.logging.LoggableElement build() {
      com.google.template.soy.logging.LoggableElement result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.google.template.soy.logging.LoggableElement buildPartial() {
      com.google.template.soy.logging.LoggableElement result = new com.google.template.soy.logging.LoggableElement(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.google.template.soy.logging.LoggableElement result) {
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.name_ = name_;
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.id_ = id_;
        to_bitField0_ |= 0x00000002;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.protoType_ = protoType_;
        to_bitField0_ |= 0x00000004;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.metadata_ = metadataBuilder_ == null
            ? metadata_
            : metadataBuilder_.build();
        to_bitField0_ |= 0x00000008;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.google.template.soy.logging.LoggableElement) {
        return mergeFrom((com.google.template.soy.logging.LoggableElement)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.google.template.soy.logging.LoggableElement other) {
      if (other == com.google.template.soy.logging.LoggableElement.getDefaultInstance()) return this;
      if (other.hasName()) {
        name_ = other.name_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (other.hasId()) {
        setId(other.getId());
      }
      if (other.hasProtoType()) {
        protoType_ = other.protoType_;
        bitField0_ |= 0x00000004;
        onChanged();
      }
      if (other.hasMetadata()) {
        mergeMetadata(other.getMetadata());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      if (hasMetadata()) {
        if (!getMetadata().isInitialized()) {
          return false;
        }
      }
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              name_ = input.readBytes();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 16: {
              id_ = input.readInt64();
              bitField0_ |= 0x00000002;
              break;
            } // case 16
            case 26: {
              protoType_ = input.readBytes();
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            case 34: {
              input.readMessage(
                  getMetadataFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000008;
              break;
            } // case 34
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object name_ = "";
    /**
     * <pre>
     * The name specified by users in the soy file.  This should be a valid
     * soy identifier (it should match:
     * '[a-zA-Z_][a-zA-Z_0-9]*([.][a-zA-Z_][a-zA-Z_0-9]*)*' )
     * Must be unique.
     * </pre>
     *
     * <code>optional string name = 1;</code>
     * @return Whether the name field is set.
     */
    public boolean hasName() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <pre>
     * The name specified by users in the soy file.  This should be a valid
     * soy identifier (it should match:
     * '[a-zA-Z_][a-zA-Z_0-9]*([.][a-zA-Z_][a-zA-Z_0-9]*)*' )
     * Must be unique.
     * </pre>
     *
     * <code>optional string name = 1;</code>
     * @return The name.
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          name_ = s;
        }
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * The name specified by users in the soy file.  This should be a valid
     * soy identifier (it should match:
     * '[a-zA-Z_][a-zA-Z_0-9]*([.][a-zA-Z_][a-zA-Z_0-9]*)*' )
     * Must be unique.
     * </pre>
     *
     * <code>optional string name = 1;</code>
     * @return The bytes for name.
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * The name specified by users in the soy file.  This should be a valid
     * soy identifier (it should match:
     * '[a-zA-Z_][a-zA-Z_0-9]*([.][a-zA-Z_][a-zA-Z_0-9]*)*' )
     * Must be unique.
     * </pre>
     *
     * <code>optional string name = 1;</code>
     * @param value The name to set.
     * @return This builder for chaining.
     */
    public Builder setName(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      name_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The name specified by users in the soy file.  This should be a valid
     * soy identifier (it should match:
     * '[a-zA-Z_][a-zA-Z_0-9]*([.][a-zA-Z_][a-zA-Z_0-9]*)*' )
     * Must be unique.
     * </pre>
     *
     * <code>optional string name = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearName() {
      name_ = getDefaultInstance().getName();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The name specified by users in the soy file.  This should be a valid
     * soy identifier (it should match:
     * '[a-zA-Z_][a-zA-Z_0-9]*([.][a-zA-Z_][a-zA-Z_0-9]*)*' )
     * Must be unique.
     * </pre>
     *
     * <code>optional string name = 1;</code>
     * @param value The bytes for name to set.
     * @return This builder for chaining.
     */
    public Builder setNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      name_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private long id_ ;
    /**
     * <pre>
     * The id that will be logged.  Must be unique.
     * </pre>
     *
     * <code>optional int64 id = 2;</code>
     * @return Whether the id field is set.
     */
    @java.lang.Override
    public boolean hasId() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <pre>
     * The id that will be logged.  Must be unique.
     * </pre>
     *
     * <code>optional int64 id = 2;</code>
     * @return The id.
     */
    @java.lang.Override
    public long getId() {
      return id_;
    }
    /**
     * <pre>
     * The id that will be logged.  Must be unique.
     * </pre>
     *
     * <code>optional int64 id = 2;</code>
     * @param value The id to set.
     * @return This builder for chaining.
     */
    public Builder setId(long value) {

      id_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The id that will be logged.  Must be unique.
     * </pre>
     *
     * <code>optional int64 id = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearId() {
      bitField0_ = (bitField0_ & ~0x00000002);
      id_ = 0L;
      onChanged();
      return this;
    }

    private java.lang.Object protoType_ = "";
    /**
     * <pre>
     * The fully qualified name of the protocol buffer that
     * will be used to specify metadata for the element.  Allowed to be the empty
     * string if there is no such proto.
     * </pre>
     *
     * <code>optional string proto_type = 3;</code>
     * @return Whether the protoType field is set.
     */
    public boolean hasProtoType() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <pre>
     * The fully qualified name of the protocol buffer that
     * will be used to specify metadata for the element.  Allowed to be the empty
     * string if there is no such proto.
     * </pre>
     *
     * <code>optional string proto_type = 3;</code>
     * @return The protoType.
     */
    public java.lang.String getProtoType() {
      java.lang.Object ref = protoType_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          protoType_ = s;
        }
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * The fully qualified name of the protocol buffer that
     * will be used to specify metadata for the element.  Allowed to be the empty
     * string if there is no such proto.
     * </pre>
     *
     * <code>optional string proto_type = 3;</code>
     * @return The bytes for protoType.
     */
    public com.google.protobuf.ByteString
        getProtoTypeBytes() {
      java.lang.Object ref = protoType_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        protoType_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * The fully qualified name of the protocol buffer that
     * will be used to specify metadata for the element.  Allowed to be the empty
     * string if there is no such proto.
     * </pre>
     *
     * <code>optional string proto_type = 3;</code>
     * @param value The protoType to set.
     * @return This builder for chaining.
     */
    public Builder setProtoType(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      protoType_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The fully qualified name of the protocol buffer that
     * will be used to specify metadata for the element.  Allowed to be the empty
     * string if there is no such proto.
     * </pre>
     *
     * <code>optional string proto_type = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearProtoType() {
      protoType_ = getDefaultInstance().getProtoType();
      bitField0_ = (bitField0_ & ~0x00000004);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The fully qualified name of the protocol buffer that
     * will be used to specify metadata for the element.  Allowed to be the empty
     * string if there is no such proto.
     * </pre>
     *
     * <code>optional string proto_type = 3;</code>
     * @param value The bytes for protoType to set.
     * @return This builder for chaining.
     */
    public Builder setProtoTypeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      protoType_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }

    private com.google.template.soy.logging.LoggableElementMetadata metadata_;
    private com.google.protobuf.SingleFieldBuilder<
        com.google.template.soy.logging.LoggableElementMetadata, com.google.template.soy.logging.LoggableElementMetadata.Builder, com.google.template.soy.logging.LoggableElementMetadataOrBuilder> metadataBuilder_;
    /**
     * <pre>
     * Additional metadata to be included with this loggable element. Use this to
     * set compile-time constant VE metadata, that will be available from Soy
     * source code.
     * </pre>
     *
     * <code>optional .soy.LoggableElementMetadata metadata = 4;</code>
     * @return Whether the metadata field is set.
     */
    public boolean hasMetadata() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <pre>
     * Additional metadata to be included with this loggable element. Use this to
     * set compile-time constant VE metadata, that will be available from Soy
     * source code.
     * </pre>
     *
     * <code>optional .soy.LoggableElementMetadata metadata = 4;</code>
     * @return The metadata.
     */
    public com.google.template.soy.logging.LoggableElementMetadata getMetadata() {
      if (metadataBuilder_ == null) {
        return metadata_ == null ? com.google.template.soy.logging.LoggableElementMetadata.getDefaultInstance() : metadata_;
      } else {
        return metadataBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * Additional metadata to be included with this loggable element. Use this to
     * set compile-time constant VE metadata, that will be available from Soy
     * source code.
     * </pre>
     *
     * <code>optional .soy.LoggableElementMetadata metadata = 4;</code>
     */
    public Builder setMetadata(com.google.template.soy.logging.LoggableElementMetadata value) {
      if (metadataBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        metadata_ = value;
      } else {
        metadataBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Additional metadata to be included with this loggable element. Use this to
     * set compile-time constant VE metadata, that will be available from Soy
     * source code.
     * </pre>
     *
     * <code>optional .soy.LoggableElementMetadata metadata = 4;</code>
     */
    public Builder setMetadata(
        com.google.template.soy.logging.LoggableElementMetadata.Builder builderForValue) {
      if (metadataBuilder_ == null) {
        metadata_ = builderForValue.build();
      } else {
        metadataBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Additional metadata to be included with this loggable element. Use this to
     * set compile-time constant VE metadata, that will be available from Soy
     * source code.
     * </pre>
     *
     * <code>optional .soy.LoggableElementMetadata metadata = 4;</code>
     */
    public Builder mergeMetadata(com.google.template.soy.logging.LoggableElementMetadata value) {
      if (metadataBuilder_ == null) {
        if (((bitField0_ & 0x00000008) != 0) &&
          metadata_ != null &&
          metadata_ != com.google.template.soy.logging.LoggableElementMetadata.getDefaultInstance()) {
          getMetadataBuilder().mergeFrom(value);
        } else {
          metadata_ = value;
        }
      } else {
        metadataBuilder_.mergeFrom(value);
      }
      if (metadata_ != null) {
        bitField0_ |= 0x00000008;
        onChanged();
      }
      return this;
    }
    /**
     * <pre>
     * Additional metadata to be included with this loggable element. Use this to
     * set compile-time constant VE metadata, that will be available from Soy
     * source code.
     * </pre>
     *
     * <code>optional .soy.LoggableElementMetadata metadata = 4;</code>
     */
    public Builder clearMetadata() {
      bitField0_ = (bitField0_ & ~0x00000008);
      metadata_ = null;
      if (metadataBuilder_ != null) {
        metadataBuilder_.dispose();
        metadataBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Additional metadata to be included with this loggable element. Use this to
     * set compile-time constant VE metadata, that will be available from Soy
     * source code.
     * </pre>
     *
     * <code>optional .soy.LoggableElementMetadata metadata = 4;</code>
     */
    public com.google.template.soy.logging.LoggableElementMetadata.Builder getMetadataBuilder() {
      bitField0_ |= 0x00000008;
      onChanged();
      return getMetadataFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * Additional metadata to be included with this loggable element. Use this to
     * set compile-time constant VE metadata, that will be available from Soy
     * source code.
     * </pre>
     *
     * <code>optional .soy.LoggableElementMetadata metadata = 4;</code>
     */
    public com.google.template.soy.logging.LoggableElementMetadataOrBuilder getMetadataOrBuilder() {
      if (metadataBuilder_ != null) {
        return metadataBuilder_.getMessageOrBuilder();
      } else {
        return metadata_ == null ?
            com.google.template.soy.logging.LoggableElementMetadata.getDefaultInstance() : metadata_;
      }
    }
    /**
     * <pre>
     * Additional metadata to be included with this loggable element. Use this to
     * set compile-time constant VE metadata, that will be available from Soy
     * source code.
     * </pre>
     *
     * <code>optional .soy.LoggableElementMetadata metadata = 4;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        com.google.template.soy.logging.LoggableElementMetadata, com.google.template.soy.logging.LoggableElementMetadata.Builder, com.google.template.soy.logging.LoggableElementMetadataOrBuilder> 
        getMetadataFieldBuilder() {
      if (metadataBuilder_ == null) {
        metadataBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            com.google.template.soy.logging.LoggableElementMetadata, com.google.template.soy.logging.LoggableElementMetadata.Builder, com.google.template.soy.logging.LoggableElementMetadataOrBuilder>(
                getMetadata(),
                getParentForChildren(),
                isClean());
        metadata_ = null;
      }
      return metadataBuilder_;
    }

    // @@protoc_insertion_point(builder_scope:soy.LoggableElement)
  }

  // @@protoc_insertion_point(class_scope:soy.LoggableElement)
  private static final com.google.template.soy.logging.LoggableElement DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.google.template.soy.logging.LoggableElement();
  }

  public static com.google.template.soy.logging.LoggableElement getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<LoggableElement>
      PARSER = new com.google.protobuf.AbstractParser<LoggableElement>() {
    @java.lang.Override
    public LoggableElement parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<LoggableElement> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<LoggableElement> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.template.soy.logging.LoggableElement getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

