// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: src/main/protobuf/template_metadata.proto
// Protobuf Java Version: 4.28.2

package com.google.template.soy.soytree;

public interface DataAllCallSituationPOrBuilder extends
    // @@protoc_insertion_point(interface_extends:soy.compiler.DataAllCallSituationP)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * The template name.
   * if this is a delcall or a call to a template in another file, this will be
   * fully qualified.  If it is a call to a template in the current namespace
   * it will be prefixed with a single dot.
   * </pre>
   *
   * <code>string template_name = 1;</code>
   * @return The templateName.
   */
  java.lang.String getTemplateName();
  /**
   * <pre>
   * The template name.
   * if this is a delcall or a call to a template in another file, this will be
   * fully qualified.  If it is a call to a template in the current namespace
   * it will be prefixed with a single dot.
   * </pre>
   *
   * <code>string template_name = 1;</code>
   * @return The bytes for templateName.
   */
  com.google.protobuf.ByteString
      getTemplateNameBytes();

  /**
   * <pre>
   * Whether this is a delcall
   * </pre>
   *
   * <code>bool del_call = 2;</code>
   * @return The delCall.
   */
  boolean getDelCall();

  /**
   * <pre>
   * The names of the explicitly passed parameters.
   * </pre>
   *
   * <code>repeated string explicitly_passed_parameters = 3;</code>
   * @return A list containing the explicitlyPassedParameters.
   */
  java.util.List<java.lang.String>
      getExplicitlyPassedParametersList();
  /**
   * <pre>
   * The names of the explicitly passed parameters.
   * </pre>
   *
   * <code>repeated string explicitly_passed_parameters = 3;</code>
   * @return The count of explicitlyPassedParameters.
   */
  int getExplicitlyPassedParametersCount();
  /**
   * <pre>
   * The names of the explicitly passed parameters.
   * </pre>
   *
   * <code>repeated string explicitly_passed_parameters = 3;</code>
   * @param index The index of the element to return.
   * @return The explicitlyPassedParameters at the given index.
   */
  java.lang.String getExplicitlyPassedParameters(int index);
  /**
   * <pre>
   * The names of the explicitly passed parameters.
   * </pre>
   *
   * <code>repeated string explicitly_passed_parameters = 3;</code>
   * @param index The index of the value to return.
   * @return The bytes of the explicitlyPassedParameters at the given index.
   */
  com.google.protobuf.ByteString
      getExplicitlyPassedParametersBytes(int index);
}
