// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: src/main/protobuf/template_metadata.proto
// Protobuf Java Version: 4.28.2

package com.google.template.soy.soytree;

/**
 * <pre>
 * Represents a call within a template.
 * </pre>
 *
 * Protobuf type {@code soy.compiler.DataAllCallSituationP}
 */
public final class DataAllCallSituationP extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:soy.compiler.DataAllCallSituationP)
    DataAllCallSituationPOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 28,
      /* patch= */ 2,
      /* suffix= */ "",
      DataAllCallSituationP.class.getName());
  }
  // Use DataAllCallSituationP.newBuilder() to construct.
  private DataAllCallSituationP(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private DataAllCallSituationP() {
    templateName_ = "";
    explicitlyPassedParameters_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.google.template.soy.soytree.TemplateMetadataProto.internal_static_soy_compiler_DataAllCallSituationP_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.google.template.soy.soytree.TemplateMetadataProto.internal_static_soy_compiler_DataAllCallSituationP_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.google.template.soy.soytree.DataAllCallSituationP.class, com.google.template.soy.soytree.DataAllCallSituationP.Builder.class);
  }

  public static final int TEMPLATE_NAME_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object templateName_ = "";
  /**
   * <pre>
   * The template name.
   * if this is a delcall or a call to a template in another file, this will be
   * fully qualified.  If it is a call to a template in the current namespace
   * it will be prefixed with a single dot.
   * </pre>
   *
   * <code>string template_name = 1;</code>
   * @return The templateName.
   */
  @java.lang.Override
  public java.lang.String getTemplateName() {
    java.lang.Object ref = templateName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      templateName_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * The template name.
   * if this is a delcall or a call to a template in another file, this will be
   * fully qualified.  If it is a call to a template in the current namespace
   * it will be prefixed with a single dot.
   * </pre>
   *
   * <code>string template_name = 1;</code>
   * @return The bytes for templateName.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getTemplateNameBytes() {
    java.lang.Object ref = templateName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      templateName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DEL_CALL_FIELD_NUMBER = 2;
  private boolean delCall_ = false;
  /**
   * <pre>
   * Whether this is a delcall
   * </pre>
   *
   * <code>bool del_call = 2;</code>
   * @return The delCall.
   */
  @java.lang.Override
  public boolean getDelCall() {
    return delCall_;
  }

  public static final int EXPLICITLY_PASSED_PARAMETERS_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private com.google.protobuf.LazyStringArrayList explicitlyPassedParameters_ =
      com.google.protobuf.LazyStringArrayList.emptyList();
  /**
   * <pre>
   * The names of the explicitly passed parameters.
   * </pre>
   *
   * <code>repeated string explicitly_passed_parameters = 3;</code>
   * @return A list containing the explicitlyPassedParameters.
   */
  public com.google.protobuf.ProtocolStringList
      getExplicitlyPassedParametersList() {
    return explicitlyPassedParameters_;
  }
  /**
   * <pre>
   * The names of the explicitly passed parameters.
   * </pre>
   *
   * <code>repeated string explicitly_passed_parameters = 3;</code>
   * @return The count of explicitlyPassedParameters.
   */
  public int getExplicitlyPassedParametersCount() {
    return explicitlyPassedParameters_.size();
  }
  /**
   * <pre>
   * The names of the explicitly passed parameters.
   * </pre>
   *
   * <code>repeated string explicitly_passed_parameters = 3;</code>
   * @param index The index of the element to return.
   * @return The explicitlyPassedParameters at the given index.
   */
  public java.lang.String getExplicitlyPassedParameters(int index) {
    return explicitlyPassedParameters_.get(index);
  }
  /**
   * <pre>
   * The names of the explicitly passed parameters.
   * </pre>
   *
   * <code>repeated string explicitly_passed_parameters = 3;</code>
   * @param index The index of the value to return.
   * @return The bytes of the explicitlyPassedParameters at the given index.
   */
  public com.google.protobuf.ByteString
      getExplicitlyPassedParametersBytes(int index) {
    return explicitlyPassedParameters_.getByteString(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(templateName_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 1, templateName_);
    }
    if (delCall_ != false) {
      output.writeBool(2, delCall_);
    }
    for (int i = 0; i < explicitlyPassedParameters_.size(); i++) {
      com.google.protobuf.GeneratedMessage.writeString(output, 3, explicitlyPassedParameters_.getRaw(i));
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(templateName_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(1, templateName_);
    }
    if (delCall_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(2, delCall_);
    }
    {
      int dataSize = 0;
      for (int i = 0; i < explicitlyPassedParameters_.size(); i++) {
        dataSize += computeStringSizeNoTag(explicitlyPassedParameters_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getExplicitlyPassedParametersList().size();
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.google.template.soy.soytree.DataAllCallSituationP)) {
      return super.equals(obj);
    }
    com.google.template.soy.soytree.DataAllCallSituationP other = (com.google.template.soy.soytree.DataAllCallSituationP) obj;

    if (!getTemplateName()
        .equals(other.getTemplateName())) return false;
    if (getDelCall()
        != other.getDelCall()) return false;
    if (!getExplicitlyPassedParametersList()
        .equals(other.getExplicitlyPassedParametersList())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + TEMPLATE_NAME_FIELD_NUMBER;
    hash = (53 * hash) + getTemplateName().hashCode();
    hash = (37 * hash) + DEL_CALL_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getDelCall());
    if (getExplicitlyPassedParametersCount() > 0) {
      hash = (37 * hash) + EXPLICITLY_PASSED_PARAMETERS_FIELD_NUMBER;
      hash = (53 * hash) + getExplicitlyPassedParametersList().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.google.template.soy.soytree.DataAllCallSituationP parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.google.template.soy.soytree.DataAllCallSituationP parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.google.template.soy.soytree.DataAllCallSituationP parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.google.template.soy.soytree.DataAllCallSituationP parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.google.template.soy.soytree.DataAllCallSituationP parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.google.template.soy.soytree.DataAllCallSituationP parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.google.template.soy.soytree.DataAllCallSituationP parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.google.template.soy.soytree.DataAllCallSituationP parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.google.template.soy.soytree.DataAllCallSituationP parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.google.template.soy.soytree.DataAllCallSituationP parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.google.template.soy.soytree.DataAllCallSituationP parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.google.template.soy.soytree.DataAllCallSituationP parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.google.template.soy.soytree.DataAllCallSituationP prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * Represents a call within a template.
   * </pre>
   *
   * Protobuf type {@code soy.compiler.DataAllCallSituationP}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:soy.compiler.DataAllCallSituationP)
      com.google.template.soy.soytree.DataAllCallSituationPOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.google.template.soy.soytree.TemplateMetadataProto.internal_static_soy_compiler_DataAllCallSituationP_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.google.template.soy.soytree.TemplateMetadataProto.internal_static_soy_compiler_DataAllCallSituationP_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.google.template.soy.soytree.DataAllCallSituationP.class, com.google.template.soy.soytree.DataAllCallSituationP.Builder.class);
    }

    // Construct using com.google.template.soy.soytree.DataAllCallSituationP.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      templateName_ = "";
      delCall_ = false;
      explicitlyPassedParameters_ =
          com.google.protobuf.LazyStringArrayList.emptyList();
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.google.template.soy.soytree.TemplateMetadataProto.internal_static_soy_compiler_DataAllCallSituationP_descriptor;
    }

    @java.lang.Override
    public com.google.template.soy.soytree.DataAllCallSituationP getDefaultInstanceForType() {
      return com.google.template.soy.soytree.DataAllCallSituationP.getDefaultInstance();
    }

    @java.lang.Override
    public com.google.template.soy.soytree.DataAllCallSituationP build() {
      com.google.template.soy.soytree.DataAllCallSituationP result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.google.template.soy.soytree.DataAllCallSituationP buildPartial() {
      com.google.template.soy.soytree.DataAllCallSituationP result = new com.google.template.soy.soytree.DataAllCallSituationP(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.google.template.soy.soytree.DataAllCallSituationP result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.templateName_ = templateName_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.delCall_ = delCall_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        explicitlyPassedParameters_.makeImmutable();
        result.explicitlyPassedParameters_ = explicitlyPassedParameters_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.google.template.soy.soytree.DataAllCallSituationP) {
        return mergeFrom((com.google.template.soy.soytree.DataAllCallSituationP)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.google.template.soy.soytree.DataAllCallSituationP other) {
      if (other == com.google.template.soy.soytree.DataAllCallSituationP.getDefaultInstance()) return this;
      if (!other.getTemplateName().isEmpty()) {
        templateName_ = other.templateName_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (other.getDelCall() != false) {
        setDelCall(other.getDelCall());
      }
      if (!other.explicitlyPassedParameters_.isEmpty()) {
        if (explicitlyPassedParameters_.isEmpty()) {
          explicitlyPassedParameters_ = other.explicitlyPassedParameters_;
          bitField0_ |= 0x00000004;
        } else {
          ensureExplicitlyPassedParametersIsMutable();
          explicitlyPassedParameters_.addAll(other.explicitlyPassedParameters_);
        }
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              templateName_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 16: {
              delCall_ = input.readBool();
              bitField0_ |= 0x00000002;
              break;
            } // case 16
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();
              ensureExplicitlyPassedParametersIsMutable();
              explicitlyPassedParameters_.add(s);
              break;
            } // case 26
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object templateName_ = "";
    /**
     * <pre>
     * The template name.
     * if this is a delcall or a call to a template in another file, this will be
     * fully qualified.  If it is a call to a template in the current namespace
     * it will be prefixed with a single dot.
     * </pre>
     *
     * <code>string template_name = 1;</code>
     * @return The templateName.
     */
    public java.lang.String getTemplateName() {
      java.lang.Object ref = templateName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        templateName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * The template name.
     * if this is a delcall or a call to a template in another file, this will be
     * fully qualified.  If it is a call to a template in the current namespace
     * it will be prefixed with a single dot.
     * </pre>
     *
     * <code>string template_name = 1;</code>
     * @return The bytes for templateName.
     */
    public com.google.protobuf.ByteString
        getTemplateNameBytes() {
      java.lang.Object ref = templateName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        templateName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * The template name.
     * if this is a delcall or a call to a template in another file, this will be
     * fully qualified.  If it is a call to a template in the current namespace
     * it will be prefixed with a single dot.
     * </pre>
     *
     * <code>string template_name = 1;</code>
     * @param value The templateName to set.
     * @return This builder for chaining.
     */
    public Builder setTemplateName(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      templateName_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The template name.
     * if this is a delcall or a call to a template in another file, this will be
     * fully qualified.  If it is a call to a template in the current namespace
     * it will be prefixed with a single dot.
     * </pre>
     *
     * <code>string template_name = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearTemplateName() {
      templateName_ = getDefaultInstance().getTemplateName();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The template name.
     * if this is a delcall or a call to a template in another file, this will be
     * fully qualified.  If it is a call to a template in the current namespace
     * it will be prefixed with a single dot.
     * </pre>
     *
     * <code>string template_name = 1;</code>
     * @param value The bytes for templateName to set.
     * @return This builder for chaining.
     */
    public Builder setTemplateNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      templateName_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private boolean delCall_ ;
    /**
     * <pre>
     * Whether this is a delcall
     * </pre>
     *
     * <code>bool del_call = 2;</code>
     * @return The delCall.
     */
    @java.lang.Override
    public boolean getDelCall() {
      return delCall_;
    }
    /**
     * <pre>
     * Whether this is a delcall
     * </pre>
     *
     * <code>bool del_call = 2;</code>
     * @param value The delCall to set.
     * @return This builder for chaining.
     */
    public Builder setDelCall(boolean value) {

      delCall_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Whether this is a delcall
     * </pre>
     *
     * <code>bool del_call = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearDelCall() {
      bitField0_ = (bitField0_ & ~0x00000002);
      delCall_ = false;
      onChanged();
      return this;
    }

    private com.google.protobuf.LazyStringArrayList explicitlyPassedParameters_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
    private void ensureExplicitlyPassedParametersIsMutable() {
      if (!explicitlyPassedParameters_.isModifiable()) {
        explicitlyPassedParameters_ = new com.google.protobuf.LazyStringArrayList(explicitlyPassedParameters_);
      }
      bitField0_ |= 0x00000004;
    }
    /**
     * <pre>
     * The names of the explicitly passed parameters.
     * </pre>
     *
     * <code>repeated string explicitly_passed_parameters = 3;</code>
     * @return A list containing the explicitlyPassedParameters.
     */
    public com.google.protobuf.ProtocolStringList
        getExplicitlyPassedParametersList() {
      explicitlyPassedParameters_.makeImmutable();
      return explicitlyPassedParameters_;
    }
    /**
     * <pre>
     * The names of the explicitly passed parameters.
     * </pre>
     *
     * <code>repeated string explicitly_passed_parameters = 3;</code>
     * @return The count of explicitlyPassedParameters.
     */
    public int getExplicitlyPassedParametersCount() {
      return explicitlyPassedParameters_.size();
    }
    /**
     * <pre>
     * The names of the explicitly passed parameters.
     * </pre>
     *
     * <code>repeated string explicitly_passed_parameters = 3;</code>
     * @param index The index of the element to return.
     * @return The explicitlyPassedParameters at the given index.
     */
    public java.lang.String getExplicitlyPassedParameters(int index) {
      return explicitlyPassedParameters_.get(index);
    }
    /**
     * <pre>
     * The names of the explicitly passed parameters.
     * </pre>
     *
     * <code>repeated string explicitly_passed_parameters = 3;</code>
     * @param index The index of the value to return.
     * @return The bytes of the explicitlyPassedParameters at the given index.
     */
    public com.google.protobuf.ByteString
        getExplicitlyPassedParametersBytes(int index) {
      return explicitlyPassedParameters_.getByteString(index);
    }
    /**
     * <pre>
     * The names of the explicitly passed parameters.
     * </pre>
     *
     * <code>repeated string explicitly_passed_parameters = 3;</code>
     * @param index The index to set the value at.
     * @param value The explicitlyPassedParameters to set.
     * @return This builder for chaining.
     */
    public Builder setExplicitlyPassedParameters(
        int index, java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      ensureExplicitlyPassedParametersIsMutable();
      explicitlyPassedParameters_.set(index, value);
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The names of the explicitly passed parameters.
     * </pre>
     *
     * <code>repeated string explicitly_passed_parameters = 3;</code>
     * @param value The explicitlyPassedParameters to add.
     * @return This builder for chaining.
     */
    public Builder addExplicitlyPassedParameters(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      ensureExplicitlyPassedParametersIsMutable();
      explicitlyPassedParameters_.add(value);
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The names of the explicitly passed parameters.
     * </pre>
     *
     * <code>repeated string explicitly_passed_parameters = 3;</code>
     * @param values The explicitlyPassedParameters to add.
     * @return This builder for chaining.
     */
    public Builder addAllExplicitlyPassedParameters(
        java.lang.Iterable<java.lang.String> values) {
      ensureExplicitlyPassedParametersIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, explicitlyPassedParameters_);
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The names of the explicitly passed parameters.
     * </pre>
     *
     * <code>repeated string explicitly_passed_parameters = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearExplicitlyPassedParameters() {
      explicitlyPassedParameters_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
      bitField0_ = (bitField0_ & ~0x00000004);;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The names of the explicitly passed parameters.
     * </pre>
     *
     * <code>repeated string explicitly_passed_parameters = 3;</code>
     * @param value The bytes of the explicitlyPassedParameters to add.
     * @return This builder for chaining.
     */
    public Builder addExplicitlyPassedParametersBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      ensureExplicitlyPassedParametersIsMutable();
      explicitlyPassedParameters_.add(value);
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:soy.compiler.DataAllCallSituationP)
  }

  // @@protoc_insertion_point(class_scope:soy.compiler.DataAllCallSituationP)
  private static final com.google.template.soy.soytree.DataAllCallSituationP DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.google.template.soy.soytree.DataAllCallSituationP();
  }

  public static com.google.template.soy.soytree.DataAllCallSituationP getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<DataAllCallSituationP>
      PARSER = new com.google.protobuf.AbstractParser<DataAllCallSituationP>() {
    @java.lang.Override
    public DataAllCallSituationP parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<DataAllCallSituationP> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<DataAllCallSituationP> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.template.soy.soytree.DataAllCallSituationP getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

