// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: src/main/protobuf/template_metadata.proto
// Protobuf Java Version: 4.28.2

package com.google.template.soy.soytree;

/**
 * <pre>
 * Metadata around whether the template contains fragments, html elements
 * or velog.
 * </pre>
 *
 * Protobuf type {@code soy.compiler.HtmlElementMetadataP}
 */
public final class HtmlElementMetadataP extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:soy.compiler.HtmlElementMetadataP)
    HtmlElementMetadataPOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 28,
      /* patch= */ 2,
      /* suffix= */ "",
      HtmlElementMetadataP.class.getName());
  }
  // Use HtmlElementMetadataP.newBuilder() to construct.
  private HtmlElementMetadataP(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private HtmlElementMetadataP() {
    tag_ = "";
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.google.template.soy.soytree.TemplateMetadataProto.internal_static_soy_compiler_HtmlElementMetadataP_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.google.template.soy.soytree.TemplateMetadataProto.internal_static_soy_compiler_HtmlElementMetadataP_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.google.template.soy.soytree.HtmlElementMetadataP.class, com.google.template.soy.soytree.HtmlElementMetadataP.Builder.class);
  }

  public static final int IS_HTML_ELEMENT_FIELD_NUMBER = 1;
  private boolean isHtmlElement_ = false;
  /**
   * <pre>
   * If this is true, then the template contains either one visible HTML
   * tag, or does a call that resolves to one HTML tag. If false, then
   * there is a fragment. This is also false if the HTML element has dynamic
   * number of tags due to if or switch statements.
   * </pre>
   *
   * <code>bool is_html_element = 1;</code>
   * @return The isHtmlElement.
   */
  @java.lang.Override
  public boolean getIsHtmlElement() {
    return isHtmlElement_;
  }

  public static final int IS_VELOGGED_FIELD_NUMBER = 2;
  private boolean isVelogged_ = false;
  /**
   * <pre>
   * If this is true, then the single element has a velog around it. This is
   * to prevent wrapping a velog around a call that is itself velogged.
   * </pre>
   *
   * <code>bool is_velogged = 2;</code>
   * @return The isVelogged.
   */
  @java.lang.Override
  public boolean getIsVelogged() {
    return isVelogged_;
  }

  public static final int TAG_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private volatile java.lang.Object tag_ = "";
  /**
   * <pre>
   * The tag of an element. If the template is a fragment or a template
   * contains a dynamic tag, then this will be "?".
   * </pre>
   *
   * <code>string tag = 3;</code>
   * @return The tag.
   */
  @java.lang.Override
  public java.lang.String getTag() {
    java.lang.Object ref = tag_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      tag_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * The tag of an element. If the template is a fragment or a template
   * contains a dynamic tag, then this will be "?".
   * </pre>
   *
   * <code>string tag = 3;</code>
   * @return The bytes for tag.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getTagBytes() {
    java.lang.Object ref = tag_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      tag_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int IS_SKIP_FIELD_NUMBER = 4;
  private boolean isSkip_ = false;
  /**
   * <pre>
   * Whether or not a template contains an element with {skip} directive.
   * </pre>
   *
   * <code>bool is_skip = 4;</code>
   * @return The isSkip.
   */
  @java.lang.Override
  public boolean getIsSkip() {
    return isSkip_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (isHtmlElement_ != false) {
      output.writeBool(1, isHtmlElement_);
    }
    if (isVelogged_ != false) {
      output.writeBool(2, isVelogged_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(tag_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 3, tag_);
    }
    if (isSkip_ != false) {
      output.writeBool(4, isSkip_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (isHtmlElement_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(1, isHtmlElement_);
    }
    if (isVelogged_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(2, isVelogged_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(tag_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(3, tag_);
    }
    if (isSkip_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(4, isSkip_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.google.template.soy.soytree.HtmlElementMetadataP)) {
      return super.equals(obj);
    }
    com.google.template.soy.soytree.HtmlElementMetadataP other = (com.google.template.soy.soytree.HtmlElementMetadataP) obj;

    if (getIsHtmlElement()
        != other.getIsHtmlElement()) return false;
    if (getIsVelogged()
        != other.getIsVelogged()) return false;
    if (!getTag()
        .equals(other.getTag())) return false;
    if (getIsSkip()
        != other.getIsSkip()) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + IS_HTML_ELEMENT_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getIsHtmlElement());
    hash = (37 * hash) + IS_VELOGGED_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getIsVelogged());
    hash = (37 * hash) + TAG_FIELD_NUMBER;
    hash = (53 * hash) + getTag().hashCode();
    hash = (37 * hash) + IS_SKIP_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getIsSkip());
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.google.template.soy.soytree.HtmlElementMetadataP parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.google.template.soy.soytree.HtmlElementMetadataP parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.google.template.soy.soytree.HtmlElementMetadataP parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.google.template.soy.soytree.HtmlElementMetadataP parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.google.template.soy.soytree.HtmlElementMetadataP parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.google.template.soy.soytree.HtmlElementMetadataP parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.google.template.soy.soytree.HtmlElementMetadataP parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.google.template.soy.soytree.HtmlElementMetadataP parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.google.template.soy.soytree.HtmlElementMetadataP parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.google.template.soy.soytree.HtmlElementMetadataP parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.google.template.soy.soytree.HtmlElementMetadataP parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.google.template.soy.soytree.HtmlElementMetadataP parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.google.template.soy.soytree.HtmlElementMetadataP prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * Metadata around whether the template contains fragments, html elements
   * or velog.
   * </pre>
   *
   * Protobuf type {@code soy.compiler.HtmlElementMetadataP}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:soy.compiler.HtmlElementMetadataP)
      com.google.template.soy.soytree.HtmlElementMetadataPOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.google.template.soy.soytree.TemplateMetadataProto.internal_static_soy_compiler_HtmlElementMetadataP_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.google.template.soy.soytree.TemplateMetadataProto.internal_static_soy_compiler_HtmlElementMetadataP_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.google.template.soy.soytree.HtmlElementMetadataP.class, com.google.template.soy.soytree.HtmlElementMetadataP.Builder.class);
    }

    // Construct using com.google.template.soy.soytree.HtmlElementMetadataP.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      isHtmlElement_ = false;
      isVelogged_ = false;
      tag_ = "";
      isSkip_ = false;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.google.template.soy.soytree.TemplateMetadataProto.internal_static_soy_compiler_HtmlElementMetadataP_descriptor;
    }

    @java.lang.Override
    public com.google.template.soy.soytree.HtmlElementMetadataP getDefaultInstanceForType() {
      return com.google.template.soy.soytree.HtmlElementMetadataP.getDefaultInstance();
    }

    @java.lang.Override
    public com.google.template.soy.soytree.HtmlElementMetadataP build() {
      com.google.template.soy.soytree.HtmlElementMetadataP result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.google.template.soy.soytree.HtmlElementMetadataP buildPartial() {
      com.google.template.soy.soytree.HtmlElementMetadataP result = new com.google.template.soy.soytree.HtmlElementMetadataP(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.google.template.soy.soytree.HtmlElementMetadataP result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.isHtmlElement_ = isHtmlElement_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.isVelogged_ = isVelogged_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.tag_ = tag_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.isSkip_ = isSkip_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.google.template.soy.soytree.HtmlElementMetadataP) {
        return mergeFrom((com.google.template.soy.soytree.HtmlElementMetadataP)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.google.template.soy.soytree.HtmlElementMetadataP other) {
      if (other == com.google.template.soy.soytree.HtmlElementMetadataP.getDefaultInstance()) return this;
      if (other.getIsHtmlElement() != false) {
        setIsHtmlElement(other.getIsHtmlElement());
      }
      if (other.getIsVelogged() != false) {
        setIsVelogged(other.getIsVelogged());
      }
      if (!other.getTag().isEmpty()) {
        tag_ = other.tag_;
        bitField0_ |= 0x00000004;
        onChanged();
      }
      if (other.getIsSkip() != false) {
        setIsSkip(other.getIsSkip());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              isHtmlElement_ = input.readBool();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 16: {
              isVelogged_ = input.readBool();
              bitField0_ |= 0x00000002;
              break;
            } // case 16
            case 26: {
              tag_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            case 32: {
              isSkip_ = input.readBool();
              bitField0_ |= 0x00000008;
              break;
            } // case 32
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private boolean isHtmlElement_ ;
    /**
     * <pre>
     * If this is true, then the template contains either one visible HTML
     * tag, or does a call that resolves to one HTML tag. If false, then
     * there is a fragment. This is also false if the HTML element has dynamic
     * number of tags due to if or switch statements.
     * </pre>
     *
     * <code>bool is_html_element = 1;</code>
     * @return The isHtmlElement.
     */
    @java.lang.Override
    public boolean getIsHtmlElement() {
      return isHtmlElement_;
    }
    /**
     * <pre>
     * If this is true, then the template contains either one visible HTML
     * tag, or does a call that resolves to one HTML tag. If false, then
     * there is a fragment. This is also false if the HTML element has dynamic
     * number of tags due to if or switch statements.
     * </pre>
     *
     * <code>bool is_html_element = 1;</code>
     * @param value The isHtmlElement to set.
     * @return This builder for chaining.
     */
    public Builder setIsHtmlElement(boolean value) {

      isHtmlElement_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * If this is true, then the template contains either one visible HTML
     * tag, or does a call that resolves to one HTML tag. If false, then
     * there is a fragment. This is also false if the HTML element has dynamic
     * number of tags due to if or switch statements.
     * </pre>
     *
     * <code>bool is_html_element = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearIsHtmlElement() {
      bitField0_ = (bitField0_ & ~0x00000001);
      isHtmlElement_ = false;
      onChanged();
      return this;
    }

    private boolean isVelogged_ ;
    /**
     * <pre>
     * If this is true, then the single element has a velog around it. This is
     * to prevent wrapping a velog around a call that is itself velogged.
     * </pre>
     *
     * <code>bool is_velogged = 2;</code>
     * @return The isVelogged.
     */
    @java.lang.Override
    public boolean getIsVelogged() {
      return isVelogged_;
    }
    /**
     * <pre>
     * If this is true, then the single element has a velog around it. This is
     * to prevent wrapping a velog around a call that is itself velogged.
     * </pre>
     *
     * <code>bool is_velogged = 2;</code>
     * @param value The isVelogged to set.
     * @return This builder for chaining.
     */
    public Builder setIsVelogged(boolean value) {

      isVelogged_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * If this is true, then the single element has a velog around it. This is
     * to prevent wrapping a velog around a call that is itself velogged.
     * </pre>
     *
     * <code>bool is_velogged = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearIsVelogged() {
      bitField0_ = (bitField0_ & ~0x00000002);
      isVelogged_ = false;
      onChanged();
      return this;
    }

    private java.lang.Object tag_ = "";
    /**
     * <pre>
     * The tag of an element. If the template is a fragment or a template
     * contains a dynamic tag, then this will be "?".
     * </pre>
     *
     * <code>string tag = 3;</code>
     * @return The tag.
     */
    public java.lang.String getTag() {
      java.lang.Object ref = tag_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        tag_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * The tag of an element. If the template is a fragment or a template
     * contains a dynamic tag, then this will be "?".
     * </pre>
     *
     * <code>string tag = 3;</code>
     * @return The bytes for tag.
     */
    public com.google.protobuf.ByteString
        getTagBytes() {
      java.lang.Object ref = tag_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        tag_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * The tag of an element. If the template is a fragment or a template
     * contains a dynamic tag, then this will be "?".
     * </pre>
     *
     * <code>string tag = 3;</code>
     * @param value The tag to set.
     * @return This builder for chaining.
     */
    public Builder setTag(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      tag_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The tag of an element. If the template is a fragment or a template
     * contains a dynamic tag, then this will be "?".
     * </pre>
     *
     * <code>string tag = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearTag() {
      tag_ = getDefaultInstance().getTag();
      bitField0_ = (bitField0_ & ~0x00000004);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The tag of an element. If the template is a fragment or a template
     * contains a dynamic tag, then this will be "?".
     * </pre>
     *
     * <code>string tag = 3;</code>
     * @param value The bytes for tag to set.
     * @return This builder for chaining.
     */
    public Builder setTagBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      tag_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }

    private boolean isSkip_ ;
    /**
     * <pre>
     * Whether or not a template contains an element with {skip} directive.
     * </pre>
     *
     * <code>bool is_skip = 4;</code>
     * @return The isSkip.
     */
    @java.lang.Override
    public boolean getIsSkip() {
      return isSkip_;
    }
    /**
     * <pre>
     * Whether or not a template contains an element with {skip} directive.
     * </pre>
     *
     * <code>bool is_skip = 4;</code>
     * @param value The isSkip to set.
     * @return This builder for chaining.
     */
    public Builder setIsSkip(boolean value) {

      isSkip_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Whether or not a template contains an element with {skip} directive.
     * </pre>
     *
     * <code>bool is_skip = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearIsSkip() {
      bitField0_ = (bitField0_ & ~0x00000008);
      isSkip_ = false;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:soy.compiler.HtmlElementMetadataP)
  }

  // @@protoc_insertion_point(class_scope:soy.compiler.HtmlElementMetadataP)
  private static final com.google.template.soy.soytree.HtmlElementMetadataP DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.google.template.soy.soytree.HtmlElementMetadataP();
  }

  public static com.google.template.soy.soytree.HtmlElementMetadataP getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<HtmlElementMetadataP>
      PARSER = new com.google.protobuf.AbstractParser<HtmlElementMetadataP>() {
    @java.lang.Override
    public HtmlElementMetadataP parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<HtmlElementMetadataP> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<HtmlElementMetadataP> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.template.soy.soytree.HtmlElementMetadataP getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

