// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: src/main/protobuf/template_metadata.proto
// Protobuf Java Version: 4.28.2

package com.google.template.soy.soytree;

public interface ParameterPOrBuilder extends
    // @@protoc_insertion_point(interface_extends:soy.compiler.ParameterP)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * The parameter name
   * </pre>
   *
   * <code>string name = 1;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <pre>
   * The parameter name
   * </pre>
   *
   * <code>string name = 1;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <pre>
   * The type of the parameter.
   * </pre>
   *
   * <code>.soy.compiler.SoyTypeP type = 2;</code>
   * @return Whether the type field is set.
   */
  boolean hasType();
  /**
   * <pre>
   * The type of the parameter.
   * </pre>
   *
   * <code>.soy.compiler.SoyTypeP type = 2;</code>
   * @return The type.
   */
  com.google.template.soy.soytree.SoyTypeP getType();
  /**
   * <pre>
   * The type of the parameter.
   * </pre>
   *
   * <code>.soy.compiler.SoyTypeP type = 2;</code>
   */
  com.google.template.soy.soytree.SoyTypePOrBuilder getTypeOrBuilder();

  /**
   * <pre>
   * Whether or not the parameter is required.
   * </pre>
   *
   * <code>bool required = 3;</code>
   * @return The required.
   */
  boolean getRequired();
}
