// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: src/main/protobuf/template_metadata.proto
// Protobuf Java Version: 4.28.2

package com.google.template.soy.soytree;

/**
 * <pre>
 * A single declared template parameter
 * </pre>
 *
 * Protobuf type {@code soy.compiler.ParameterP}
 */
public final class ParameterP extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:soy.compiler.ParameterP)
    ParameterPOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 28,
      /* patch= */ 2,
      /* suffix= */ "",
      ParameterP.class.getName());
  }
  // Use ParameterP.newBuilder() to construct.
  private ParameterP(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private ParameterP() {
    name_ = "";
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.google.template.soy.soytree.TemplateMetadataProto.internal_static_soy_compiler_ParameterP_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.google.template.soy.soytree.TemplateMetadataProto.internal_static_soy_compiler_ParameterP_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.google.template.soy.soytree.ParameterP.class, com.google.template.soy.soytree.ParameterP.Builder.class);
  }

  private int bitField0_;
  public static final int NAME_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object name_ = "";
  /**
   * <pre>
   * The parameter name
   * </pre>
   *
   * <code>string name = 1;</code>
   * @return The name.
   */
  @java.lang.Override
  public java.lang.String getName() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      name_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * The parameter name
   * </pre>
   *
   * <code>string name = 1;</code>
   * @return The bytes for name.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getNameBytes() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      name_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TYPE_FIELD_NUMBER = 2;
  private com.google.template.soy.soytree.SoyTypeP type_;
  /**
   * <pre>
   * The type of the parameter.
   * </pre>
   *
   * <code>.soy.compiler.SoyTypeP type = 2;</code>
   * @return Whether the type field is set.
   */
  @java.lang.Override
  public boolean hasType() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <pre>
   * The type of the parameter.
   * </pre>
   *
   * <code>.soy.compiler.SoyTypeP type = 2;</code>
   * @return The type.
   */
  @java.lang.Override
  public com.google.template.soy.soytree.SoyTypeP getType() {
    return type_ == null ? com.google.template.soy.soytree.SoyTypeP.getDefaultInstance() : type_;
  }
  /**
   * <pre>
   * The type of the parameter.
   * </pre>
   *
   * <code>.soy.compiler.SoyTypeP type = 2;</code>
   */
  @java.lang.Override
  public com.google.template.soy.soytree.SoyTypePOrBuilder getTypeOrBuilder() {
    return type_ == null ? com.google.template.soy.soytree.SoyTypeP.getDefaultInstance() : type_;
  }

  public static final int REQUIRED_FIELD_NUMBER = 3;
  private boolean required_ = false;
  /**
   * <pre>
   * Whether or not the parameter is required.
   * </pre>
   *
   * <code>bool required = 3;</code>
   * @return The required.
   */
  @java.lang.Override
  public boolean getRequired() {
    return required_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(name_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 1, name_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(2, getType());
    }
    if (required_ != false) {
      output.writeBool(3, required_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(name_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(1, name_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getType());
    }
    if (required_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(3, required_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.google.template.soy.soytree.ParameterP)) {
      return super.equals(obj);
    }
    com.google.template.soy.soytree.ParameterP other = (com.google.template.soy.soytree.ParameterP) obj;

    if (!getName()
        .equals(other.getName())) return false;
    if (hasType() != other.hasType()) return false;
    if (hasType()) {
      if (!getType()
          .equals(other.getType())) return false;
    }
    if (getRequired()
        != other.getRequired()) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + NAME_FIELD_NUMBER;
    hash = (53 * hash) + getName().hashCode();
    if (hasType()) {
      hash = (37 * hash) + TYPE_FIELD_NUMBER;
      hash = (53 * hash) + getType().hashCode();
    }
    hash = (37 * hash) + REQUIRED_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getRequired());
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.google.template.soy.soytree.ParameterP parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.google.template.soy.soytree.ParameterP parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.google.template.soy.soytree.ParameterP parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.google.template.soy.soytree.ParameterP parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.google.template.soy.soytree.ParameterP parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.google.template.soy.soytree.ParameterP parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.google.template.soy.soytree.ParameterP parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.google.template.soy.soytree.ParameterP parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.google.template.soy.soytree.ParameterP parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.google.template.soy.soytree.ParameterP parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.google.template.soy.soytree.ParameterP parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.google.template.soy.soytree.ParameterP parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.google.template.soy.soytree.ParameterP prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * A single declared template parameter
   * </pre>
   *
   * Protobuf type {@code soy.compiler.ParameterP}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:soy.compiler.ParameterP)
      com.google.template.soy.soytree.ParameterPOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.google.template.soy.soytree.TemplateMetadataProto.internal_static_soy_compiler_ParameterP_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.google.template.soy.soytree.TemplateMetadataProto.internal_static_soy_compiler_ParameterP_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.google.template.soy.soytree.ParameterP.class, com.google.template.soy.soytree.ParameterP.Builder.class);
    }

    // Construct using com.google.template.soy.soytree.ParameterP.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage
              .alwaysUseFieldBuilders) {
        getTypeFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      name_ = "";
      type_ = null;
      if (typeBuilder_ != null) {
        typeBuilder_.dispose();
        typeBuilder_ = null;
      }
      required_ = false;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.google.template.soy.soytree.TemplateMetadataProto.internal_static_soy_compiler_ParameterP_descriptor;
    }

    @java.lang.Override
    public com.google.template.soy.soytree.ParameterP getDefaultInstanceForType() {
      return com.google.template.soy.soytree.ParameterP.getDefaultInstance();
    }

    @java.lang.Override
    public com.google.template.soy.soytree.ParameterP build() {
      com.google.template.soy.soytree.ParameterP result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.google.template.soy.soytree.ParameterP buildPartial() {
      com.google.template.soy.soytree.ParameterP result = new com.google.template.soy.soytree.ParameterP(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.google.template.soy.soytree.ParameterP result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.name_ = name_;
      }
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.type_ = typeBuilder_ == null
            ? type_
            : typeBuilder_.build();
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.required_ = required_;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.google.template.soy.soytree.ParameterP) {
        return mergeFrom((com.google.template.soy.soytree.ParameterP)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.google.template.soy.soytree.ParameterP other) {
      if (other == com.google.template.soy.soytree.ParameterP.getDefaultInstance()) return this;
      if (!other.getName().isEmpty()) {
        name_ = other.name_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (other.hasType()) {
        mergeType(other.getType());
      }
      if (other.getRequired() != false) {
        setRequired(other.getRequired());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              name_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              input.readMessage(
                  getTypeFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 24: {
              required_ = input.readBool();
              bitField0_ |= 0x00000004;
              break;
            } // case 24
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object name_ = "";
    /**
     * <pre>
     * The parameter name
     * </pre>
     *
     * <code>string name = 1;</code>
     * @return The name.
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * The parameter name
     * </pre>
     *
     * <code>string name = 1;</code>
     * @return The bytes for name.
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * The parameter name
     * </pre>
     *
     * <code>string name = 1;</code>
     * @param value The name to set.
     * @return This builder for chaining.
     */
    public Builder setName(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      name_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The parameter name
     * </pre>
     *
     * <code>string name = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearName() {
      name_ = getDefaultInstance().getName();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The parameter name
     * </pre>
     *
     * <code>string name = 1;</code>
     * @param value The bytes for name to set.
     * @return This builder for chaining.
     */
    public Builder setNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      name_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private com.google.template.soy.soytree.SoyTypeP type_;
    private com.google.protobuf.SingleFieldBuilder<
        com.google.template.soy.soytree.SoyTypeP, com.google.template.soy.soytree.SoyTypeP.Builder, com.google.template.soy.soytree.SoyTypePOrBuilder> typeBuilder_;
    /**
     * <pre>
     * The type of the parameter.
     * </pre>
     *
     * <code>.soy.compiler.SoyTypeP type = 2;</code>
     * @return Whether the type field is set.
     */
    public boolean hasType() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <pre>
     * The type of the parameter.
     * </pre>
     *
     * <code>.soy.compiler.SoyTypeP type = 2;</code>
     * @return The type.
     */
    public com.google.template.soy.soytree.SoyTypeP getType() {
      if (typeBuilder_ == null) {
        return type_ == null ? com.google.template.soy.soytree.SoyTypeP.getDefaultInstance() : type_;
      } else {
        return typeBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * The type of the parameter.
     * </pre>
     *
     * <code>.soy.compiler.SoyTypeP type = 2;</code>
     */
    public Builder setType(com.google.template.soy.soytree.SoyTypeP value) {
      if (typeBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        type_ = value;
      } else {
        typeBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The type of the parameter.
     * </pre>
     *
     * <code>.soy.compiler.SoyTypeP type = 2;</code>
     */
    public Builder setType(
        com.google.template.soy.soytree.SoyTypeP.Builder builderForValue) {
      if (typeBuilder_ == null) {
        type_ = builderForValue.build();
      } else {
        typeBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The type of the parameter.
     * </pre>
     *
     * <code>.soy.compiler.SoyTypeP type = 2;</code>
     */
    public Builder mergeType(com.google.template.soy.soytree.SoyTypeP value) {
      if (typeBuilder_ == null) {
        if (((bitField0_ & 0x00000002) != 0) &&
          type_ != null &&
          type_ != com.google.template.soy.soytree.SoyTypeP.getDefaultInstance()) {
          getTypeBuilder().mergeFrom(value);
        } else {
          type_ = value;
        }
      } else {
        typeBuilder_.mergeFrom(value);
      }
      if (type_ != null) {
        bitField0_ |= 0x00000002;
        onChanged();
      }
      return this;
    }
    /**
     * <pre>
     * The type of the parameter.
     * </pre>
     *
     * <code>.soy.compiler.SoyTypeP type = 2;</code>
     */
    public Builder clearType() {
      bitField0_ = (bitField0_ & ~0x00000002);
      type_ = null;
      if (typeBuilder_ != null) {
        typeBuilder_.dispose();
        typeBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The type of the parameter.
     * </pre>
     *
     * <code>.soy.compiler.SoyTypeP type = 2;</code>
     */
    public com.google.template.soy.soytree.SoyTypeP.Builder getTypeBuilder() {
      bitField0_ |= 0x00000002;
      onChanged();
      return getTypeFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * The type of the parameter.
     * </pre>
     *
     * <code>.soy.compiler.SoyTypeP type = 2;</code>
     */
    public com.google.template.soy.soytree.SoyTypePOrBuilder getTypeOrBuilder() {
      if (typeBuilder_ != null) {
        return typeBuilder_.getMessageOrBuilder();
      } else {
        return type_ == null ?
            com.google.template.soy.soytree.SoyTypeP.getDefaultInstance() : type_;
      }
    }
    /**
     * <pre>
     * The type of the parameter.
     * </pre>
     *
     * <code>.soy.compiler.SoyTypeP type = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        com.google.template.soy.soytree.SoyTypeP, com.google.template.soy.soytree.SoyTypeP.Builder, com.google.template.soy.soytree.SoyTypePOrBuilder> 
        getTypeFieldBuilder() {
      if (typeBuilder_ == null) {
        typeBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            com.google.template.soy.soytree.SoyTypeP, com.google.template.soy.soytree.SoyTypeP.Builder, com.google.template.soy.soytree.SoyTypePOrBuilder>(
                getType(),
                getParentForChildren(),
                isClean());
        type_ = null;
      }
      return typeBuilder_;
    }

    private boolean required_ ;
    /**
     * <pre>
     * Whether or not the parameter is required.
     * </pre>
     *
     * <code>bool required = 3;</code>
     * @return The required.
     */
    @java.lang.Override
    public boolean getRequired() {
      return required_;
    }
    /**
     * <pre>
     * Whether or not the parameter is required.
     * </pre>
     *
     * <code>bool required = 3;</code>
     * @param value The required to set.
     * @return This builder for chaining.
     */
    public Builder setRequired(boolean value) {

      required_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Whether or not the parameter is required.
     * </pre>
     *
     * <code>bool required = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearRequired() {
      bitField0_ = (bitField0_ & ~0x00000004);
      required_ = false;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:soy.compiler.ParameterP)
  }

  // @@protoc_insertion_point(class_scope:soy.compiler.ParameterP)
  private static final com.google.template.soy.soytree.ParameterP DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.google.template.soy.soytree.ParameterP();
  }

  public static com.google.template.soy.soytree.ParameterP getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ParameterP>
      PARSER = new com.google.protobuf.AbstractParser<ParameterP>() {
    @java.lang.Override
    public ParameterP parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<ParameterP> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ParameterP> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.template.soy.soytree.ParameterP getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

