// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: src/main/protobuf/template_metadata.proto
// Protobuf Java Version: 4.28.2

package com.google.template.soy.soytree;

/**
 * <pre>
 * A duplicate of SanitizedContentKind
 * </pre>
 *
 * Protobuf enum {@code soy.compiler.SanitizedContentKindP}
 */
public enum SanitizedContentKindP
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>UNKNOWN_SANITIZED_CONTENT_KIND = 0;</code>
   */
  UNKNOWN_SANITIZED_CONTENT_KIND(0),
  /**
   * <code>HTML = 1;</code>
   */
  HTML(1),
  /**
   * <code>JS = 2;</code>
   */
  JS(2),
  /**
   * <code>URI = 3;</code>
   */
  URI(3),
  /**
   * <code>TRUSTED_RESOURCE_URI = 4;</code>
   */
  TRUSTED_RESOURCE_URI(4),
  /**
   * <code>ATTRIBUTES = 5;</code>
   */
  ATTRIBUTES(5),
  /**
   * <code>CSS = 6;</code>
   */
  CSS(6),
  /**
   * <code>TEXT = 7;</code>
   */
  TEXT(7),
  /**
   * <code>NONE = 8;</code>
   */
  NONE(8),
  UNRECOGNIZED(-1),
  ;

  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 28,
      /* patch= */ 2,
      /* suffix= */ "",
      SanitizedContentKindP.class.getName());
  }
  /**
   * <code>UNKNOWN_SANITIZED_CONTENT_KIND = 0;</code>
   */
  public static final int UNKNOWN_SANITIZED_CONTENT_KIND_VALUE = 0;
  /**
   * <code>HTML = 1;</code>
   */
  public static final int HTML_VALUE = 1;
  /**
   * <code>JS = 2;</code>
   */
  public static final int JS_VALUE = 2;
  /**
   * <code>URI = 3;</code>
   */
  public static final int URI_VALUE = 3;
  /**
   * <code>TRUSTED_RESOURCE_URI = 4;</code>
   */
  public static final int TRUSTED_RESOURCE_URI_VALUE = 4;
  /**
   * <code>ATTRIBUTES = 5;</code>
   */
  public static final int ATTRIBUTES_VALUE = 5;
  /**
   * <code>CSS = 6;</code>
   */
  public static final int CSS_VALUE = 6;
  /**
   * <code>TEXT = 7;</code>
   */
  public static final int TEXT_VALUE = 7;
  /**
   * <code>NONE = 8;</code>
   */
  public static final int NONE_VALUE = 8;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static SanitizedContentKindP valueOf(int value) {
    return forNumber(value);
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   */
  public static SanitizedContentKindP forNumber(int value) {
    switch (value) {
      case 0: return UNKNOWN_SANITIZED_CONTENT_KIND;
      case 1: return HTML;
      case 2: return JS;
      case 3: return URI;
      case 4: return TRUSTED_RESOURCE_URI;
      case 5: return ATTRIBUTES;
      case 6: return CSS;
      case 7: return TEXT;
      case 8: return NONE;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<SanitizedContentKindP>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      SanitizedContentKindP> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<SanitizedContentKindP>() {
          public SanitizedContentKindP findValueByNumber(int number) {
            return SanitizedContentKindP.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalStateException(
          "Can't get the descriptor of an unrecognized enum value.");
    }
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return com.google.template.soy.soytree.TemplateMetadataProto.getDescriptor().getEnumTypes().get(0);
  }

  private static final SanitizedContentKindP[] VALUES = values();

  public static SanitizedContentKindP valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private SanitizedContentKindP(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:soy.compiler.SanitizedContentKindP)
}

