// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: src/main/protobuf/template_metadata.proto
// Protobuf Java Version: 4.28.2

package com.google.template.soy.soytree;

/**
 * <pre>
 * Metadata around whether the template is a Soy element or not.
 * </pre>
 *
 * Protobuf type {@code soy.compiler.SoyElementMetadataP}
 */
public final class SoyElementMetadataP extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:soy.compiler.SoyElementMetadataP)
    SoyElementMetadataPOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 28,
      /* patch= */ 2,
      /* suffix= */ "",
      SoyElementMetadataP.class.getName());
  }
  // Use SoyElementMetadataP.newBuilder() to construct.
  private SoyElementMetadataP(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private SoyElementMetadataP() {
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.google.template.soy.soytree.TemplateMetadataProto.internal_static_soy_compiler_SoyElementMetadataP_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.google.template.soy.soytree.TemplateMetadataProto.internal_static_soy_compiler_SoyElementMetadataP_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.google.template.soy.soytree.SoyElementMetadataP.class, com.google.template.soy.soytree.SoyElementMetadataP.Builder.class);
  }

  public static final int IS_SOY_ELEMENT_FIELD_NUMBER = 1;
  private boolean isSoyElement_ = false;
  /**
   * <code>bool is_soy_element = 1;</code>
   * @return The isSoyElement.
   */
  @java.lang.Override
  public boolean getIsSoyElement() {
    return isSoyElement_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (isSoyElement_ != false) {
      output.writeBool(1, isSoyElement_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (isSoyElement_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(1, isSoyElement_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.google.template.soy.soytree.SoyElementMetadataP)) {
      return super.equals(obj);
    }
    com.google.template.soy.soytree.SoyElementMetadataP other = (com.google.template.soy.soytree.SoyElementMetadataP) obj;

    if (getIsSoyElement()
        != other.getIsSoyElement()) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + IS_SOY_ELEMENT_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getIsSoyElement());
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.google.template.soy.soytree.SoyElementMetadataP parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.google.template.soy.soytree.SoyElementMetadataP parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.google.template.soy.soytree.SoyElementMetadataP parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.google.template.soy.soytree.SoyElementMetadataP parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.google.template.soy.soytree.SoyElementMetadataP parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.google.template.soy.soytree.SoyElementMetadataP parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.google.template.soy.soytree.SoyElementMetadataP parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.google.template.soy.soytree.SoyElementMetadataP parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.google.template.soy.soytree.SoyElementMetadataP parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.google.template.soy.soytree.SoyElementMetadataP parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.google.template.soy.soytree.SoyElementMetadataP parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.google.template.soy.soytree.SoyElementMetadataP parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.google.template.soy.soytree.SoyElementMetadataP prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * Metadata around whether the template is a Soy element or not.
   * </pre>
   *
   * Protobuf type {@code soy.compiler.SoyElementMetadataP}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:soy.compiler.SoyElementMetadataP)
      com.google.template.soy.soytree.SoyElementMetadataPOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.google.template.soy.soytree.TemplateMetadataProto.internal_static_soy_compiler_SoyElementMetadataP_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.google.template.soy.soytree.TemplateMetadataProto.internal_static_soy_compiler_SoyElementMetadataP_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.google.template.soy.soytree.SoyElementMetadataP.class, com.google.template.soy.soytree.SoyElementMetadataP.Builder.class);
    }

    // Construct using com.google.template.soy.soytree.SoyElementMetadataP.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      isSoyElement_ = false;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.google.template.soy.soytree.TemplateMetadataProto.internal_static_soy_compiler_SoyElementMetadataP_descriptor;
    }

    @java.lang.Override
    public com.google.template.soy.soytree.SoyElementMetadataP getDefaultInstanceForType() {
      return com.google.template.soy.soytree.SoyElementMetadataP.getDefaultInstance();
    }

    @java.lang.Override
    public com.google.template.soy.soytree.SoyElementMetadataP build() {
      com.google.template.soy.soytree.SoyElementMetadataP result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.google.template.soy.soytree.SoyElementMetadataP buildPartial() {
      com.google.template.soy.soytree.SoyElementMetadataP result = new com.google.template.soy.soytree.SoyElementMetadataP(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.google.template.soy.soytree.SoyElementMetadataP result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.isSoyElement_ = isSoyElement_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.google.template.soy.soytree.SoyElementMetadataP) {
        return mergeFrom((com.google.template.soy.soytree.SoyElementMetadataP)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.google.template.soy.soytree.SoyElementMetadataP other) {
      if (other == com.google.template.soy.soytree.SoyElementMetadataP.getDefaultInstance()) return this;
      if (other.getIsSoyElement() != false) {
        setIsSoyElement(other.getIsSoyElement());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              isSoyElement_ = input.readBool();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private boolean isSoyElement_ ;
    /**
     * <code>bool is_soy_element = 1;</code>
     * @return The isSoyElement.
     */
    @java.lang.Override
    public boolean getIsSoyElement() {
      return isSoyElement_;
    }
    /**
     * <code>bool is_soy_element = 1;</code>
     * @param value The isSoyElement to set.
     * @return This builder for chaining.
     */
    public Builder setIsSoyElement(boolean value) {

      isSoyElement_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>bool is_soy_element = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearIsSoyElement() {
      bitField0_ = (bitField0_ & ~0x00000001);
      isSoyElement_ = false;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:soy.compiler.SoyElementMetadataP)
  }

  // @@protoc_insertion_point(class_scope:soy.compiler.SoyElementMetadataP)
  private static final com.google.template.soy.soytree.SoyElementMetadataP DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.google.template.soy.soytree.SoyElementMetadataP();
  }

  public static com.google.template.soy.soytree.SoyElementMetadataP getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<SoyElementMetadataP>
      PARSER = new com.google.protobuf.AbstractParser<SoyElementMetadataP>() {
    @java.lang.Override
    public SoyElementMetadataP parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<SoyElementMetadataP> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<SoyElementMetadataP> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.template.soy.soytree.SoyElementMetadataP getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

