// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: src/main/protobuf/template_metadata.proto
// Protobuf Java Version: 4.28.2

package com.google.template.soy.soytree;

public interface SoyElementMetadataPOrBuilder extends
    // @@protoc_insertion_point(interface_extends:soy.compiler.SoyElementMetadataP)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool is_soy_element = 1;</code>
   * @return The isSoyElement.
   */
  boolean getIsSoyElement();
}
