// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: src/main/protobuf/template_metadata.proto
// Protobuf Java Version: 4.28.2

package com.google.template.soy.soytree;

/**
 * <pre>
 * Represents a soy file
 * File global information should be represented here to avoid duplicating data
 * across each template.
 * </pre>
 *
 * Protobuf type {@code soy.compiler.SoyFileP}
 */
public final class SoyFileP extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:soy.compiler.SoyFileP)
    SoyFilePOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 28,
      /* patch= */ 2,
      /* suffix= */ "",
      SoyFileP.class.getName());
  }
  // Use SoyFileP.newBuilder() to construct.
  private SoyFileP(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private SoyFileP() {
    filePath_ = "";
    delpackage_ = "";
    namespace_ = "";
    template_ = java.util.Collections.emptyList();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.google.template.soy.soytree.TemplateMetadataProto.internal_static_soy_compiler_SoyFileP_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.google.template.soy.soytree.TemplateMetadataProto.internal_static_soy_compiler_SoyFileP_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.google.template.soy.soytree.SoyFileP.class, com.google.template.soy.soytree.SoyFileP.Builder.class);
  }

  public static final int FILE_PATH_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object filePath_ = "";
  /**
   * <pre>
   * The original file path for the soy file.
   * </pre>
   *
   * <code>string file_path = 1;</code>
   * @return The filePath.
   */
  @java.lang.Override
  public java.lang.String getFilePath() {
    java.lang.Object ref = filePath_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      filePath_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * The original file path for the soy file.
   * </pre>
   *
   * <code>string file_path = 1;</code>
   * @return The bytes for filePath.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getFilePathBytes() {
    java.lang.Object ref = filePath_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      filePath_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DELPACKAGE_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object delpackage_ = "";
  /**
   * <pre>
   * The delpackage of the file, or "" if there was no delpackage
   * </pre>
   *
   * <code>string delpackage = 2;</code>
   * @return The delpackage.
   */
  @java.lang.Override
  public java.lang.String getDelpackage() {
    java.lang.Object ref = delpackage_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      delpackage_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * The delpackage of the file, or "" if there was no delpackage
   * </pre>
   *
   * <code>string delpackage = 2;</code>
   * @return The bytes for delpackage.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getDelpackageBytes() {
    java.lang.Object ref = delpackage_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      delpackage_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int NAMESPACE_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private volatile java.lang.Object namespace_ = "";
  /**
   * <pre>
   * The namespace of the file
   * </pre>
   *
   * <code>string namespace = 3;</code>
   * @return The namespace.
   */
  @java.lang.Override
  public java.lang.String getNamespace() {
    java.lang.Object ref = namespace_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      namespace_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * The namespace of the file
   * </pre>
   *
   * <code>string namespace = 3;</code>
   * @return The bytes for namespace.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getNamespaceBytes() {
    java.lang.Object ref = namespace_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      namespace_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TEMPLATE_FIELD_NUMBER = 4;
  @SuppressWarnings("serial")
  private java.util.List<com.google.template.soy.soytree.TemplateMetadataP> template_;
  /**
   * <pre>
   * The templates in the file
   * </pre>
   *
   * <code>repeated .soy.compiler.TemplateMetadataP template = 4;</code>
   */
  @java.lang.Override
  public java.util.List<com.google.template.soy.soytree.TemplateMetadataP> getTemplateList() {
    return template_;
  }
  /**
   * <pre>
   * The templates in the file
   * </pre>
   *
   * <code>repeated .soy.compiler.TemplateMetadataP template = 4;</code>
   */
  @java.lang.Override
  public java.util.List<? extends com.google.template.soy.soytree.TemplateMetadataPOrBuilder> 
      getTemplateOrBuilderList() {
    return template_;
  }
  /**
   * <pre>
   * The templates in the file
   * </pre>
   *
   * <code>repeated .soy.compiler.TemplateMetadataP template = 4;</code>
   */
  @java.lang.Override
  public int getTemplateCount() {
    return template_.size();
  }
  /**
   * <pre>
   * The templates in the file
   * </pre>
   *
   * <code>repeated .soy.compiler.TemplateMetadataP template = 4;</code>
   */
  @java.lang.Override
  public com.google.template.soy.soytree.TemplateMetadataP getTemplate(int index) {
    return template_.get(index);
  }
  /**
   * <pre>
   * The templates in the file
   * </pre>
   *
   * <code>repeated .soy.compiler.TemplateMetadataP template = 4;</code>
   */
  @java.lang.Override
  public com.google.template.soy.soytree.TemplateMetadataPOrBuilder getTemplateOrBuilder(
      int index) {
    return template_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(filePath_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 1, filePath_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(delpackage_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 2, delpackage_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(namespace_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 3, namespace_);
    }
    for (int i = 0; i < template_.size(); i++) {
      output.writeMessage(4, template_.get(i));
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(filePath_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(1, filePath_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(delpackage_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(2, delpackage_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(namespace_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(3, namespace_);
    }
    for (int i = 0; i < template_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, template_.get(i));
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.google.template.soy.soytree.SoyFileP)) {
      return super.equals(obj);
    }
    com.google.template.soy.soytree.SoyFileP other = (com.google.template.soy.soytree.SoyFileP) obj;

    if (!getFilePath()
        .equals(other.getFilePath())) return false;
    if (!getDelpackage()
        .equals(other.getDelpackage())) return false;
    if (!getNamespace()
        .equals(other.getNamespace())) return false;
    if (!getTemplateList()
        .equals(other.getTemplateList())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + FILE_PATH_FIELD_NUMBER;
    hash = (53 * hash) + getFilePath().hashCode();
    hash = (37 * hash) + DELPACKAGE_FIELD_NUMBER;
    hash = (53 * hash) + getDelpackage().hashCode();
    hash = (37 * hash) + NAMESPACE_FIELD_NUMBER;
    hash = (53 * hash) + getNamespace().hashCode();
    if (getTemplateCount() > 0) {
      hash = (37 * hash) + TEMPLATE_FIELD_NUMBER;
      hash = (53 * hash) + getTemplateList().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.google.template.soy.soytree.SoyFileP parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.google.template.soy.soytree.SoyFileP parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.google.template.soy.soytree.SoyFileP parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.google.template.soy.soytree.SoyFileP parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.google.template.soy.soytree.SoyFileP parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.google.template.soy.soytree.SoyFileP parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.google.template.soy.soytree.SoyFileP parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.google.template.soy.soytree.SoyFileP parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.google.template.soy.soytree.SoyFileP parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.google.template.soy.soytree.SoyFileP parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.google.template.soy.soytree.SoyFileP parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.google.template.soy.soytree.SoyFileP parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.google.template.soy.soytree.SoyFileP prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * Represents a soy file
   * File global information should be represented here to avoid duplicating data
   * across each template.
   * </pre>
   *
   * Protobuf type {@code soy.compiler.SoyFileP}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:soy.compiler.SoyFileP)
      com.google.template.soy.soytree.SoyFilePOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.google.template.soy.soytree.TemplateMetadataProto.internal_static_soy_compiler_SoyFileP_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.google.template.soy.soytree.TemplateMetadataProto.internal_static_soy_compiler_SoyFileP_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.google.template.soy.soytree.SoyFileP.class, com.google.template.soy.soytree.SoyFileP.Builder.class);
    }

    // Construct using com.google.template.soy.soytree.SoyFileP.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      filePath_ = "";
      delpackage_ = "";
      namespace_ = "";
      if (templateBuilder_ == null) {
        template_ = java.util.Collections.emptyList();
      } else {
        template_ = null;
        templateBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000008);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.google.template.soy.soytree.TemplateMetadataProto.internal_static_soy_compiler_SoyFileP_descriptor;
    }

    @java.lang.Override
    public com.google.template.soy.soytree.SoyFileP getDefaultInstanceForType() {
      return com.google.template.soy.soytree.SoyFileP.getDefaultInstance();
    }

    @java.lang.Override
    public com.google.template.soy.soytree.SoyFileP build() {
      com.google.template.soy.soytree.SoyFileP result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.google.template.soy.soytree.SoyFileP buildPartial() {
      com.google.template.soy.soytree.SoyFileP result = new com.google.template.soy.soytree.SoyFileP(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(com.google.template.soy.soytree.SoyFileP result) {
      if (templateBuilder_ == null) {
        if (((bitField0_ & 0x00000008) != 0)) {
          template_ = java.util.Collections.unmodifiableList(template_);
          bitField0_ = (bitField0_ & ~0x00000008);
        }
        result.template_ = template_;
      } else {
        result.template_ = templateBuilder_.build();
      }
    }

    private void buildPartial0(com.google.template.soy.soytree.SoyFileP result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.filePath_ = filePath_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.delpackage_ = delpackage_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.namespace_ = namespace_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.google.template.soy.soytree.SoyFileP) {
        return mergeFrom((com.google.template.soy.soytree.SoyFileP)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.google.template.soy.soytree.SoyFileP other) {
      if (other == com.google.template.soy.soytree.SoyFileP.getDefaultInstance()) return this;
      if (!other.getFilePath().isEmpty()) {
        filePath_ = other.filePath_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (!other.getDelpackage().isEmpty()) {
        delpackage_ = other.delpackage_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      if (!other.getNamespace().isEmpty()) {
        namespace_ = other.namespace_;
        bitField0_ |= 0x00000004;
        onChanged();
      }
      if (templateBuilder_ == null) {
        if (!other.template_.isEmpty()) {
          if (template_.isEmpty()) {
            template_ = other.template_;
            bitField0_ = (bitField0_ & ~0x00000008);
          } else {
            ensureTemplateIsMutable();
            template_.addAll(other.template_);
          }
          onChanged();
        }
      } else {
        if (!other.template_.isEmpty()) {
          if (templateBuilder_.isEmpty()) {
            templateBuilder_.dispose();
            templateBuilder_ = null;
            template_ = other.template_;
            bitField0_ = (bitField0_ & ~0x00000008);
            templateBuilder_ = 
              com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                 getTemplateFieldBuilder() : null;
          } else {
            templateBuilder_.addAllMessages(other.template_);
          }
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              filePath_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              delpackage_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 26: {
              namespace_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            case 34: {
              com.google.template.soy.soytree.TemplateMetadataP m =
                  input.readMessage(
                      com.google.template.soy.soytree.TemplateMetadataP.parser(),
                      extensionRegistry);
              if (templateBuilder_ == null) {
                ensureTemplateIsMutable();
                template_.add(m);
              } else {
                templateBuilder_.addMessage(m);
              }
              break;
            } // case 34
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object filePath_ = "";
    /**
     * <pre>
     * The original file path for the soy file.
     * </pre>
     *
     * <code>string file_path = 1;</code>
     * @return The filePath.
     */
    public java.lang.String getFilePath() {
      java.lang.Object ref = filePath_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        filePath_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * The original file path for the soy file.
     * </pre>
     *
     * <code>string file_path = 1;</code>
     * @return The bytes for filePath.
     */
    public com.google.protobuf.ByteString
        getFilePathBytes() {
      java.lang.Object ref = filePath_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        filePath_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * The original file path for the soy file.
     * </pre>
     *
     * <code>string file_path = 1;</code>
     * @param value The filePath to set.
     * @return This builder for chaining.
     */
    public Builder setFilePath(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      filePath_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The original file path for the soy file.
     * </pre>
     *
     * <code>string file_path = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearFilePath() {
      filePath_ = getDefaultInstance().getFilePath();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The original file path for the soy file.
     * </pre>
     *
     * <code>string file_path = 1;</code>
     * @param value The bytes for filePath to set.
     * @return This builder for chaining.
     */
    public Builder setFilePathBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      filePath_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private java.lang.Object delpackage_ = "";
    /**
     * <pre>
     * The delpackage of the file, or "" if there was no delpackage
     * </pre>
     *
     * <code>string delpackage = 2;</code>
     * @return The delpackage.
     */
    public java.lang.String getDelpackage() {
      java.lang.Object ref = delpackage_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        delpackage_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * The delpackage of the file, or "" if there was no delpackage
     * </pre>
     *
     * <code>string delpackage = 2;</code>
     * @return The bytes for delpackage.
     */
    public com.google.protobuf.ByteString
        getDelpackageBytes() {
      java.lang.Object ref = delpackage_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        delpackage_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * The delpackage of the file, or "" if there was no delpackage
     * </pre>
     *
     * <code>string delpackage = 2;</code>
     * @param value The delpackage to set.
     * @return This builder for chaining.
     */
    public Builder setDelpackage(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      delpackage_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The delpackage of the file, or "" if there was no delpackage
     * </pre>
     *
     * <code>string delpackage = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearDelpackage() {
      delpackage_ = getDefaultInstance().getDelpackage();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The delpackage of the file, or "" if there was no delpackage
     * </pre>
     *
     * <code>string delpackage = 2;</code>
     * @param value The bytes for delpackage to set.
     * @return This builder for chaining.
     */
    public Builder setDelpackageBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      delpackage_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private java.lang.Object namespace_ = "";
    /**
     * <pre>
     * The namespace of the file
     * </pre>
     *
     * <code>string namespace = 3;</code>
     * @return The namespace.
     */
    public java.lang.String getNamespace() {
      java.lang.Object ref = namespace_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        namespace_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * The namespace of the file
     * </pre>
     *
     * <code>string namespace = 3;</code>
     * @return The bytes for namespace.
     */
    public com.google.protobuf.ByteString
        getNamespaceBytes() {
      java.lang.Object ref = namespace_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        namespace_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * The namespace of the file
     * </pre>
     *
     * <code>string namespace = 3;</code>
     * @param value The namespace to set.
     * @return This builder for chaining.
     */
    public Builder setNamespace(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      namespace_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The namespace of the file
     * </pre>
     *
     * <code>string namespace = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearNamespace() {
      namespace_ = getDefaultInstance().getNamespace();
      bitField0_ = (bitField0_ & ~0x00000004);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The namespace of the file
     * </pre>
     *
     * <code>string namespace = 3;</code>
     * @param value The bytes for namespace to set.
     * @return This builder for chaining.
     */
    public Builder setNamespaceBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      namespace_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }

    private java.util.List<com.google.template.soy.soytree.TemplateMetadataP> template_ =
      java.util.Collections.emptyList();
    private void ensureTemplateIsMutable() {
      if (!((bitField0_ & 0x00000008) != 0)) {
        template_ = new java.util.ArrayList<com.google.template.soy.soytree.TemplateMetadataP>(template_);
        bitField0_ |= 0x00000008;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilder<
        com.google.template.soy.soytree.TemplateMetadataP, com.google.template.soy.soytree.TemplateMetadataP.Builder, com.google.template.soy.soytree.TemplateMetadataPOrBuilder> templateBuilder_;

    /**
     * <pre>
     * The templates in the file
     * </pre>
     *
     * <code>repeated .soy.compiler.TemplateMetadataP template = 4;</code>
     */
    public java.util.List<com.google.template.soy.soytree.TemplateMetadataP> getTemplateList() {
      if (templateBuilder_ == null) {
        return java.util.Collections.unmodifiableList(template_);
      } else {
        return templateBuilder_.getMessageList();
      }
    }
    /**
     * <pre>
     * The templates in the file
     * </pre>
     *
     * <code>repeated .soy.compiler.TemplateMetadataP template = 4;</code>
     */
    public int getTemplateCount() {
      if (templateBuilder_ == null) {
        return template_.size();
      } else {
        return templateBuilder_.getCount();
      }
    }
    /**
     * <pre>
     * The templates in the file
     * </pre>
     *
     * <code>repeated .soy.compiler.TemplateMetadataP template = 4;</code>
     */
    public com.google.template.soy.soytree.TemplateMetadataP getTemplate(int index) {
      if (templateBuilder_ == null) {
        return template_.get(index);
      } else {
        return templateBuilder_.getMessage(index);
      }
    }
    /**
     * <pre>
     * The templates in the file
     * </pre>
     *
     * <code>repeated .soy.compiler.TemplateMetadataP template = 4;</code>
     */
    public Builder setTemplate(
        int index, com.google.template.soy.soytree.TemplateMetadataP value) {
      if (templateBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureTemplateIsMutable();
        template_.set(index, value);
        onChanged();
      } else {
        templateBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * The templates in the file
     * </pre>
     *
     * <code>repeated .soy.compiler.TemplateMetadataP template = 4;</code>
     */
    public Builder setTemplate(
        int index, com.google.template.soy.soytree.TemplateMetadataP.Builder builderForValue) {
      if (templateBuilder_ == null) {
        ensureTemplateIsMutable();
        template_.set(index, builderForValue.build());
        onChanged();
      } else {
        templateBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * The templates in the file
     * </pre>
     *
     * <code>repeated .soy.compiler.TemplateMetadataP template = 4;</code>
     */
    public Builder addTemplate(com.google.template.soy.soytree.TemplateMetadataP value) {
      if (templateBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureTemplateIsMutable();
        template_.add(value);
        onChanged();
      } else {
        templateBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <pre>
     * The templates in the file
     * </pre>
     *
     * <code>repeated .soy.compiler.TemplateMetadataP template = 4;</code>
     */
    public Builder addTemplate(
        int index, com.google.template.soy.soytree.TemplateMetadataP value) {
      if (templateBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureTemplateIsMutable();
        template_.add(index, value);
        onChanged();
      } else {
        templateBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * The templates in the file
     * </pre>
     *
     * <code>repeated .soy.compiler.TemplateMetadataP template = 4;</code>
     */
    public Builder addTemplate(
        com.google.template.soy.soytree.TemplateMetadataP.Builder builderForValue) {
      if (templateBuilder_ == null) {
        ensureTemplateIsMutable();
        template_.add(builderForValue.build());
        onChanged();
      } else {
        templateBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * The templates in the file
     * </pre>
     *
     * <code>repeated .soy.compiler.TemplateMetadataP template = 4;</code>
     */
    public Builder addTemplate(
        int index, com.google.template.soy.soytree.TemplateMetadataP.Builder builderForValue) {
      if (templateBuilder_ == null) {
        ensureTemplateIsMutable();
        template_.add(index, builderForValue.build());
        onChanged();
      } else {
        templateBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * The templates in the file
     * </pre>
     *
     * <code>repeated .soy.compiler.TemplateMetadataP template = 4;</code>
     */
    public Builder addAllTemplate(
        java.lang.Iterable<? extends com.google.template.soy.soytree.TemplateMetadataP> values) {
      if (templateBuilder_ == null) {
        ensureTemplateIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, template_);
        onChanged();
      } else {
        templateBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <pre>
     * The templates in the file
     * </pre>
     *
     * <code>repeated .soy.compiler.TemplateMetadataP template = 4;</code>
     */
    public Builder clearTemplate() {
      if (templateBuilder_ == null) {
        template_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000008);
        onChanged();
      } else {
        templateBuilder_.clear();
      }
      return this;
    }
    /**
     * <pre>
     * The templates in the file
     * </pre>
     *
     * <code>repeated .soy.compiler.TemplateMetadataP template = 4;</code>
     */
    public Builder removeTemplate(int index) {
      if (templateBuilder_ == null) {
        ensureTemplateIsMutable();
        template_.remove(index);
        onChanged();
      } else {
        templateBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <pre>
     * The templates in the file
     * </pre>
     *
     * <code>repeated .soy.compiler.TemplateMetadataP template = 4;</code>
     */
    public com.google.template.soy.soytree.TemplateMetadataP.Builder getTemplateBuilder(
        int index) {
      return getTemplateFieldBuilder().getBuilder(index);
    }
    /**
     * <pre>
     * The templates in the file
     * </pre>
     *
     * <code>repeated .soy.compiler.TemplateMetadataP template = 4;</code>
     */
    public com.google.template.soy.soytree.TemplateMetadataPOrBuilder getTemplateOrBuilder(
        int index) {
      if (templateBuilder_ == null) {
        return template_.get(index);  } else {
        return templateBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <pre>
     * The templates in the file
     * </pre>
     *
     * <code>repeated .soy.compiler.TemplateMetadataP template = 4;</code>
     */
    public java.util.List<? extends com.google.template.soy.soytree.TemplateMetadataPOrBuilder> 
         getTemplateOrBuilderList() {
      if (templateBuilder_ != null) {
        return templateBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(template_);
      }
    }
    /**
     * <pre>
     * The templates in the file
     * </pre>
     *
     * <code>repeated .soy.compiler.TemplateMetadataP template = 4;</code>
     */
    public com.google.template.soy.soytree.TemplateMetadataP.Builder addTemplateBuilder() {
      return getTemplateFieldBuilder().addBuilder(
          com.google.template.soy.soytree.TemplateMetadataP.getDefaultInstance());
    }
    /**
     * <pre>
     * The templates in the file
     * </pre>
     *
     * <code>repeated .soy.compiler.TemplateMetadataP template = 4;</code>
     */
    public com.google.template.soy.soytree.TemplateMetadataP.Builder addTemplateBuilder(
        int index) {
      return getTemplateFieldBuilder().addBuilder(
          index, com.google.template.soy.soytree.TemplateMetadataP.getDefaultInstance());
    }
    /**
     * <pre>
     * The templates in the file
     * </pre>
     *
     * <code>repeated .soy.compiler.TemplateMetadataP template = 4;</code>
     */
    public java.util.List<com.google.template.soy.soytree.TemplateMetadataP.Builder> 
         getTemplateBuilderList() {
      return getTemplateFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilder<
        com.google.template.soy.soytree.TemplateMetadataP, com.google.template.soy.soytree.TemplateMetadataP.Builder, com.google.template.soy.soytree.TemplateMetadataPOrBuilder> 
        getTemplateFieldBuilder() {
      if (templateBuilder_ == null) {
        templateBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
            com.google.template.soy.soytree.TemplateMetadataP, com.google.template.soy.soytree.TemplateMetadataP.Builder, com.google.template.soy.soytree.TemplateMetadataPOrBuilder>(
                template_,
                ((bitField0_ & 0x00000008) != 0),
                getParentForChildren(),
                isClean());
        template_ = null;
      }
      return templateBuilder_;
    }

    // @@protoc_insertion_point(builder_scope:soy.compiler.SoyFileP)
  }

  // @@protoc_insertion_point(class_scope:soy.compiler.SoyFileP)
  private static final com.google.template.soy.soytree.SoyFileP DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.google.template.soy.soytree.SoyFileP();
  }

  public static com.google.template.soy.soytree.SoyFileP getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<SoyFileP>
      PARSER = new com.google.protobuf.AbstractParser<SoyFileP>() {
    @java.lang.Override
    public SoyFileP parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<SoyFileP> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<SoyFileP> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.template.soy.soytree.SoyFileP getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

