// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: src/main/protobuf/template_metadata.proto
// Protobuf Java Version: 4.28.2

package com.google.template.soy.soytree;

public interface SoyFilePOrBuilder extends
    // @@protoc_insertion_point(interface_extends:soy.compiler.SoyFileP)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * The original file path for the soy file.
   * </pre>
   *
   * <code>string file_path = 1;</code>
   * @return The filePath.
   */
  java.lang.String getFilePath();
  /**
   * <pre>
   * The original file path for the soy file.
   * </pre>
   *
   * <code>string file_path = 1;</code>
   * @return The bytes for filePath.
   */
  com.google.protobuf.ByteString
      getFilePathBytes();

  /**
   * <pre>
   * The delpackage of the file, or "" if there was no delpackage
   * </pre>
   *
   * <code>string delpackage = 2;</code>
   * @return The delpackage.
   */
  java.lang.String getDelpackage();
  /**
   * <pre>
   * The delpackage of the file, or "" if there was no delpackage
   * </pre>
   *
   * <code>string delpackage = 2;</code>
   * @return The bytes for delpackage.
   */
  com.google.protobuf.ByteString
      getDelpackageBytes();

  /**
   * <pre>
   * The namespace of the file
   * </pre>
   *
   * <code>string namespace = 3;</code>
   * @return The namespace.
   */
  java.lang.String getNamespace();
  /**
   * <pre>
   * The namespace of the file
   * </pre>
   *
   * <code>string namespace = 3;</code>
   * @return The bytes for namespace.
   */
  com.google.protobuf.ByteString
      getNamespaceBytes();

  /**
   * <pre>
   * The templates in the file
   * </pre>
   *
   * <code>repeated .soy.compiler.TemplateMetadataP template = 4;</code>
   */
  java.util.List<com.google.template.soy.soytree.TemplateMetadataP> 
      getTemplateList();
  /**
   * <pre>
   * The templates in the file
   * </pre>
   *
   * <code>repeated .soy.compiler.TemplateMetadataP template = 4;</code>
   */
  com.google.template.soy.soytree.TemplateMetadataP getTemplate(int index);
  /**
   * <pre>
   * The templates in the file
   * </pre>
   *
   * <code>repeated .soy.compiler.TemplateMetadataP template = 4;</code>
   */
  int getTemplateCount();
  /**
   * <pre>
   * The templates in the file
   * </pre>
   *
   * <code>repeated .soy.compiler.TemplateMetadataP template = 4;</code>
   */
  java.util.List<? extends com.google.template.soy.soytree.TemplateMetadataPOrBuilder> 
      getTemplateOrBuilderList();
  /**
   * <pre>
   * The templates in the file
   * </pre>
   *
   * <code>repeated .soy.compiler.TemplateMetadataP template = 4;</code>
   */
  com.google.template.soy.soytree.TemplateMetadataPOrBuilder getTemplateOrBuilder(
      int index);
}
