// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: src/main/protobuf/template_metadata.proto
// Protobuf Java Version: 4.28.2

package com.google.template.soy.soytree;

public interface SoyTypePOrBuilder extends
    // @@protoc_insertion_point(interface_extends:soy.compiler.SoyTypeP)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.soy.compiler.SoyTypeP.PrimitiveTypeP primitive = 1;</code>
   * @return Whether the primitive field is set.
   */
  boolean hasPrimitive();
  /**
   * <code>.soy.compiler.SoyTypeP.PrimitiveTypeP primitive = 1;</code>
   * @return The enum numeric value on the wire for primitive.
   */
  int getPrimitiveValue();
  /**
   * <code>.soy.compiler.SoyTypeP.PrimitiveTypeP primitive = 1;</code>
   * @return The primitive.
   */
  com.google.template.soy.soytree.SoyTypeP.PrimitiveTypeP getPrimitive();

  /**
   * <code>.soy.compiler.SoyTypeP list_element = 2;</code>
   * @return Whether the listElement field is set.
   */
  boolean hasListElement();
  /**
   * <code>.soy.compiler.SoyTypeP list_element = 2;</code>
   * @return The listElement.
   */
  com.google.template.soy.soytree.SoyTypeP getListElement();
  /**
   * <code>.soy.compiler.SoyTypeP list_element = 2;</code>
   */
  com.google.template.soy.soytree.SoyTypePOrBuilder getListElementOrBuilder();

  /**
   * <code>.soy.compiler.SoyTypeP.RecordTypeP record = 3;</code>
   * @return Whether the record field is set.
   */
  boolean hasRecord();
  /**
   * <code>.soy.compiler.SoyTypeP.RecordTypeP record = 3;</code>
   * @return The record.
   */
  com.google.template.soy.soytree.SoyTypeP.RecordTypeP getRecord();
  /**
   * <code>.soy.compiler.SoyTypeP.RecordTypeP record = 3;</code>
   */
  com.google.template.soy.soytree.SoyTypeP.RecordTypePOrBuilder getRecordOrBuilder();

  /**
   * <code>.soy.compiler.SoyTypeP.LegacyObjectMapTypeP legacy_object_map = 4;</code>
   * @return Whether the legacyObjectMap field is set.
   */
  boolean hasLegacyObjectMap();
  /**
   * <code>.soy.compiler.SoyTypeP.LegacyObjectMapTypeP legacy_object_map = 4;</code>
   * @return The legacyObjectMap.
   */
  com.google.template.soy.soytree.SoyTypeP.LegacyObjectMapTypeP getLegacyObjectMap();
  /**
   * <code>.soy.compiler.SoyTypeP.LegacyObjectMapTypeP legacy_object_map = 4;</code>
   */
  com.google.template.soy.soytree.SoyTypeP.LegacyObjectMapTypePOrBuilder getLegacyObjectMapOrBuilder();

  /**
   * <code>.soy.compiler.SoyTypeP.MapTypeP map = 5;</code>
   * @return Whether the map field is set.
   */
  boolean hasMap();
  /**
   * <code>.soy.compiler.SoyTypeP.MapTypeP map = 5;</code>
   * @return The map.
   */
  com.google.template.soy.soytree.SoyTypeP.MapTypeP getMap();
  /**
   * <code>.soy.compiler.SoyTypeP.MapTypeP map = 5;</code>
   */
  com.google.template.soy.soytree.SoyTypeP.MapTypePOrBuilder getMapOrBuilder();

  /**
   * <code>string proto = 6;</code>
   * @return Whether the proto field is set.
   */
  boolean hasProto();
  /**
   * <code>string proto = 6;</code>
   * @return The proto.
   */
  java.lang.String getProto();
  /**
   * <code>string proto = 6;</code>
   * @return The bytes for proto.
   */
  com.google.protobuf.ByteString
      getProtoBytes();

  /**
   * <code>string proto_enum = 7;</code>
   * @return Whether the protoEnum field is set.
   */
  boolean hasProtoEnum();
  /**
   * <code>string proto_enum = 7;</code>
   * @return The protoEnum.
   */
  java.lang.String getProtoEnum();
  /**
   * <code>string proto_enum = 7;</code>
   * @return The bytes for protoEnum.
   */
  com.google.protobuf.ByteString
      getProtoEnumBytes();

  /**
   * <code>.soy.compiler.SoyTypeP.UnionTypeP union = 8;</code>
   * @return Whether the union field is set.
   */
  boolean hasUnion();
  /**
   * <code>.soy.compiler.SoyTypeP.UnionTypeP union = 8;</code>
   * @return The union.
   */
  com.google.template.soy.soytree.SoyTypeP.UnionTypeP getUnion();
  /**
   * <code>.soy.compiler.SoyTypeP.UnionTypeP union = 8;</code>
   */
  com.google.template.soy.soytree.SoyTypeP.UnionTypePOrBuilder getUnionOrBuilder();

  /**
   * <code>string ve = 9;</code>
   * @return Whether the ve field is set.
   */
  boolean hasVe();
  /**
   * <code>string ve = 9;</code>
   * @return The ve.
   */
  java.lang.String getVe();
  /**
   * <code>string ve = 9;</code>
   * @return The bytes for ve.
   */
  com.google.protobuf.ByteString
      getVeBytes();

  /**
   * <code>.soy.compiler.SoyTypeP.TemplateTypeP template = 10;</code>
   * @return Whether the template field is set.
   */
  boolean hasTemplate();
  /**
   * <code>.soy.compiler.SoyTypeP.TemplateTypeP template = 10;</code>
   * @return The template.
   */
  com.google.template.soy.soytree.SoyTypeP.TemplateTypeP getTemplate();
  /**
   * <code>.soy.compiler.SoyTypeP.TemplateTypeP template = 10;</code>
   */
  com.google.template.soy.soytree.SoyTypeP.TemplateTypePOrBuilder getTemplateOrBuilder();

  /**
   * <code>bool message = 11;</code>
   * @return Whether the message field is set.
   */
  boolean hasMessage();
  /**
   * <code>bool message = 11;</code>
   * @return The message.
   */
  boolean getMessage();

  com.google.template.soy.soytree.SoyTypeP.TypeKindCase getTypeKindCase();
}
