// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: src/main/protobuf/template_metadata.proto
// Protobuf Java Version: 4.28.2

package com.google.template.soy.soytree;

public interface TemplateMetadataPOrBuilder extends
    // @@protoc_insertion_point(interface_extends:soy.compiler.TemplateMetadataP)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.soy.compiler.TemplateKindP template_kind = 1;</code>
   * @return The enum numeric value on the wire for templateKind.
   */
  int getTemplateKindValue();
  /**
   * <code>.soy.compiler.TemplateKindP template_kind = 1;</code>
   * @return The templateKind.
   */
  com.google.template.soy.soytree.TemplateKindP getTemplateKind();

  /**
   * <pre>
   * The template name.
   * For basic templates or elements this will be a partial name
   * For deltemplates it will be the fully qualified deltemplate name.
   * </pre>
   *
   * <code>string template_name = 2;</code>
   * @return The templateName.
   */
  java.lang.String getTemplateName();
  /**
   * <pre>
   * The template name.
   * For basic templates or elements this will be a partial name
   * For deltemplates it will be the fully qualified deltemplate name.
   * </pre>
   *
   * <code>string template_name = 2;</code>
   * @return The bytes for templateName.
   */
  com.google.protobuf.ByteString
      getTemplateNameBytes();

  /**
   * <pre>
   * The variant string.  Will be empty for basic templates or deltemplates with
   * no variant.
   * </pre>
   *
   * <code>string del_template_variant = 3;</code>
   * @return The delTemplateVariant.
   */
  java.lang.String getDelTemplateVariant();
  /**
   * <pre>
   * The variant string.  Will be empty for basic templates or deltemplates with
   * no variant.
   * </pre>
   *
   * <code>string del_template_variant = 3;</code>
   * @return The bytes for delTemplateVariant.
   */
  com.google.protobuf.ByteString
      getDelTemplateVariantBytes();

  /**
   * <code>.soy.compiler.SanitizedContentKindP content_kind = 4;</code>
   * @return The enum numeric value on the wire for contentKind.
   */
  int getContentKindValue();
  /**
   * <code>.soy.compiler.SanitizedContentKindP content_kind = 4;</code>
   * @return The contentKind.
   */
  com.google.template.soy.soytree.SanitizedContentKindP getContentKind();

  /**
   * <code>bool strict_html = 5;</code>
   * @return The strictHtml.
   */
  boolean getStrictHtml();

  /**
   * <code>.soy.compiler.VisibilityP visibility = 6;</code>
   * @return The enum numeric value on the wire for visibility.
   */
  int getVisibilityValue();
  /**
   * <code>.soy.compiler.VisibilityP visibility = 6;</code>
   * @return The visibility.
   */
  com.google.template.soy.soytree.VisibilityP getVisibility();

  /**
   * <code>repeated .soy.compiler.ParameterP parameter = 7;</code>
   */
  java.util.List<com.google.template.soy.soytree.ParameterP> 
      getParameterList();
  /**
   * <code>repeated .soy.compiler.ParameterP parameter = 7;</code>
   */
  com.google.template.soy.soytree.ParameterP getParameter(int index);
  /**
   * <code>repeated .soy.compiler.ParameterP parameter = 7;</code>
   */
  int getParameterCount();
  /**
   * <code>repeated .soy.compiler.ParameterP parameter = 7;</code>
   */
  java.util.List<? extends com.google.template.soy.soytree.ParameterPOrBuilder> 
      getParameterOrBuilderList();
  /**
   * <code>repeated .soy.compiler.ParameterP parameter = 7;</code>
   */
  com.google.template.soy.soytree.ParameterPOrBuilder getParameterOrBuilder(
      int index);

  /**
   * <code>repeated .soy.compiler.DataAllCallSituationP data_all_call_situation = 8;</code>
   */
  java.util.List<com.google.template.soy.soytree.DataAllCallSituationP> 
      getDataAllCallSituationList();
  /**
   * <code>repeated .soy.compiler.DataAllCallSituationP data_all_call_situation = 8;</code>
   */
  com.google.template.soy.soytree.DataAllCallSituationP getDataAllCallSituation(int index);
  /**
   * <code>repeated .soy.compiler.DataAllCallSituationP data_all_call_situation = 8;</code>
   */
  int getDataAllCallSituationCount();
  /**
   * <code>repeated .soy.compiler.DataAllCallSituationP data_all_call_situation = 8;</code>
   */
  java.util.List<? extends com.google.template.soy.soytree.DataAllCallSituationPOrBuilder> 
      getDataAllCallSituationOrBuilderList();
  /**
   * <code>repeated .soy.compiler.DataAllCallSituationP data_all_call_situation = 8;</code>
   */
  com.google.template.soy.soytree.DataAllCallSituationPOrBuilder getDataAllCallSituationOrBuilder(
      int index);

  /**
   * <code>.soy.compiler.HtmlElementMetadataP html_element = 11;</code>
   * @return Whether the htmlElement field is set.
   */
  boolean hasHtmlElement();
  /**
   * <code>.soy.compiler.HtmlElementMetadataP html_element = 11;</code>
   * @return The htmlElement.
   */
  com.google.template.soy.soytree.HtmlElementMetadataP getHtmlElement();
  /**
   * <code>.soy.compiler.HtmlElementMetadataP html_element = 11;</code>
   */
  com.google.template.soy.soytree.HtmlElementMetadataPOrBuilder getHtmlElementOrBuilder();

  /**
   * <code>.soy.compiler.SoyElementMetadataP soy_element = 12;</code>
   * @return Whether the soyElement field is set.
   */
  boolean hasSoyElement();
  /**
   * <code>.soy.compiler.SoyElementMetadataP soy_element = 12;</code>
   * @return The soyElement.
   */
  com.google.template.soy.soytree.SoyElementMetadataP getSoyElement();
  /**
   * <code>.soy.compiler.SoyElementMetadataP soy_element = 12;</code>
   */
  com.google.template.soy.soytree.SoyElementMetadataPOrBuilder getSoyElementOrBuilder();
}
