// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: src/main/protobuf/template_metadata.proto
// Protobuf Java Version: 4.28.2

package com.google.template.soy.soytree;

/**
 * <pre>
 * The kind of the template.
 * </pre>
 *
 * Protobuf enum {@code soy.compiler.TemplateKindP}
 */
public enum TemplateKindP
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>UNKNOWN_TEMPLATE_KIND = 0;</code>
   */
  UNKNOWN_TEMPLATE_KIND(0),
  /**
   * <code>BASIC = 1;</code>
   */
  BASIC(1),
  /**
   * <code>ELEMENT = 2;</code>
   */
  ELEMENT(2),
  /**
   * <code>DELTEMPLATE = 3;</code>
   */
  DELTEMPLATE(3),
  UNRECOGNIZED(-1),
  ;

  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 28,
      /* patch= */ 2,
      /* suffix= */ "",
      TemplateKindP.class.getName());
  }
  /**
   * <code>UNKNOWN_TEMPLATE_KIND = 0;</code>
   */
  public static final int UNKNOWN_TEMPLATE_KIND_VALUE = 0;
  /**
   * <code>BASIC = 1;</code>
   */
  public static final int BASIC_VALUE = 1;
  /**
   * <code>ELEMENT = 2;</code>
   */
  public static final int ELEMENT_VALUE = 2;
  /**
   * <code>DELTEMPLATE = 3;</code>
   */
  public static final int DELTEMPLATE_VALUE = 3;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static TemplateKindP valueOf(int value) {
    return forNumber(value);
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   */
  public static TemplateKindP forNumber(int value) {
    switch (value) {
      case 0: return UNKNOWN_TEMPLATE_KIND;
      case 1: return BASIC;
      case 2: return ELEMENT;
      case 3: return DELTEMPLATE;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<TemplateKindP>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      TemplateKindP> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<TemplateKindP>() {
          public TemplateKindP findValueByNumber(int number) {
            return TemplateKindP.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalStateException(
          "Can't get the descriptor of an unrecognized enum value.");
    }
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return com.google.template.soy.soytree.TemplateMetadataProto.getDescriptor().getEnumTypes().get(1);
  }

  private static final TemplateKindP[] VALUES = values();

  public static TemplateKindP valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private TemplateKindP(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:soy.compiler.TemplateKindP)
}

