// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: src/main/protobuf/template_metadata.proto
// Protobuf Java Version: 4.28.2

package com.google.template.soy.soytree;

/**
 * <pre>
 * The visibility of the template.
 * </pre>
 *
 * Protobuf enum {@code soy.compiler.VisibilityP}
 */
public enum VisibilityP
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>UNKNOWN_VISIBILITY = 0;</code>
   */
  UNKNOWN_VISIBILITY(0),
  /**
   * <code>PUBLIC = 1;</code>
   */
  PUBLIC(1),
  /**
   * <code>PRIVATE = 2;</code>
   */
  PRIVATE(2),
  UNRECOGNIZED(-1),
  ;

  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 28,
      /* patch= */ 2,
      /* suffix= */ "",
      VisibilityP.class.getName());
  }
  /**
   * <code>UNKNOWN_VISIBILITY = 0;</code>
   */
  public static final int UNKNOWN_VISIBILITY_VALUE = 0;
  /**
   * <code>PUBLIC = 1;</code>
   */
  public static final int PUBLIC_VALUE = 1;
  /**
   * <code>PRIVATE = 2;</code>
   */
  public static final int PRIVATE_VALUE = 2;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static VisibilityP valueOf(int value) {
    return forNumber(value);
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   */
  public static VisibilityP forNumber(int value) {
    switch (value) {
      case 0: return UNKNOWN_VISIBILITY;
      case 1: return PUBLIC;
      case 2: return PRIVATE;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<VisibilityP>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      VisibilityP> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<VisibilityP>() {
          public VisibilityP findValueByNumber(int number) {
            return VisibilityP.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalStateException(
          "Can't get the descriptor of an unrecognized enum value.");
    }
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return com.google.template.soy.soytree.TemplateMetadataProto.getDescriptor().getEnumTypes().get(2);
  }

  private static final VisibilityP[] VALUES = values();

  public static VisibilityP valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private VisibilityP(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:soy.compiler.VisibilityP)
}

