// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: src/main/protobuf/conformance.proto
// Protobuf Java Version: 4.28.2

package com.google.template.soy.conformance;

public final class Conformance {
  private Conformance() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 28,
      /* patch= */ 2,
      /* suffix= */ "",
      Conformance.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_soy_ConformanceConfig_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_soy_ConformanceConfig_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_soy_Requirement_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_soy_Requirement_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_soy_Requirement_BannedCssSelector_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_soy_Requirement_BannedCssSelector_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_soy_Requirement_BannedDirective_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_soy_Requirement_BannedDirective_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_soy_Requirement_BannedFunction_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_soy_Requirement_BannedFunction_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_soy_Requirement_BannedRawText_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_soy_Requirement_BannedRawText_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_soy_Requirement_BannedHtmlTag_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_soy_Requirement_BannedHtmlTag_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_soy_Requirement_BanXidForCssObfuscation_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_soy_Requirement_BanXidForCssObfuscation_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_soy_Requirement_Custom_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_soy_Requirement_Custom_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n#src/main/protobuf/conformance.proto\022\003s" +
      "oy\":\n\021ConformanceConfig\022%\n\013requirement\030\001" +
      " \003(\0132\020.soy.Requirement\"\371\006\n\013Requirement\022A" +
      "\n\023banned_css_selector\030\002 \001(\0132\".soy.Requir" +
      "ement.BannedCssSelectorH\000\022:\n\017banned_func" +
      "tion\030\003 \001(\0132\037.soy.Requirement.BannedFunct" +
      "ionH\000\022<\n\020banned_directive\030\004 \001(\0132 .soy.Re" +
      "quirement.BannedDirectiveH\000\0229\n\017banned_ra" +
      "w_text\030\005 \001(\0132\036.soy.Requirement.BannedRaw" +
      "TextH\000\022)\n\006custom\030\007 \001(\0132\027.soy.Requirement" +
      ".CustomH\000\0229\n\017banned_html_tag\030\013 \001(\0132\036.soy" +
      ".Requirement.BannedHtmlTagH\000\022O\n\033ban_xid_" +
      "for_css_obfuscation\030\016 \001(\0132(.soy.Requirem" +
      "ent.BanXidForCssObfuscationH\000\022\025\n\rerror_m" +
      "essage\030\010 \001(\t\022\016\n\006exempt\030\020 \003(\t\022\025\n\ronly_app" +
      "ly_to\030\017 \003(\t\032:\n\021BannedCssSelector\022\020\n\010sele" +
      "ctor\030\001 \003(\t\022\023\n\013when_prefix\030\002 \001(\010\032$\n\017Banne" +
      "dDirective\022\021\n\tdirective\030\001 \003(\t\032\"\n\016BannedF" +
      "unction\022\020\n\010function\030\001 \003(\t\032?\n\rBannedRawTe" +
      "xt\022\014\n\004text\030\001 \003(\t\022 \n\030except_in_html_attri" +
      "bute\030\002 \003(\t\032E\n\rBannedHtmlTag\022\013\n\003tag\030\001 \003(\t" +
      "\022\'\n\037when_attribute_possibly_present\030\002 \003(" +
      "\t\032\031\n\027BanXidForCssObfuscation\032\034\n\006Custom\022\022" +
      "\n\njava_class\030\001 \001(\tB\022\n\020requirement_typeJ\004" +
      "\010\001\020\002J\004\010\006\020\007J\004\010\014\020\rJ\004\010\r\020\016J\004\010\t\020\nJ\004\010\n\020\013B\'\n#co" +
      "m.google.template.soy.conformanceP\001b\006pro" +
      "to3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_soy_ConformanceConfig_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_soy_ConformanceConfig_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_soy_ConformanceConfig_descriptor,
        new java.lang.String[] { "Requirement", });
    internal_static_soy_Requirement_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_soy_Requirement_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_soy_Requirement_descriptor,
        new java.lang.String[] { "BannedCssSelector", "BannedFunction", "BannedDirective", "BannedRawText", "Custom", "BannedHtmlTag", "BanXidForCssObfuscation", "ErrorMessage", "Exempt", "OnlyApplyTo", "RequirementType", });
    internal_static_soy_Requirement_BannedCssSelector_descriptor =
      internal_static_soy_Requirement_descriptor.getNestedTypes().get(0);
    internal_static_soy_Requirement_BannedCssSelector_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_soy_Requirement_BannedCssSelector_descriptor,
        new java.lang.String[] { "Selector", "WhenPrefix", });
    internal_static_soy_Requirement_BannedDirective_descriptor =
      internal_static_soy_Requirement_descriptor.getNestedTypes().get(1);
    internal_static_soy_Requirement_BannedDirective_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_soy_Requirement_BannedDirective_descriptor,
        new java.lang.String[] { "Directive", });
    internal_static_soy_Requirement_BannedFunction_descriptor =
      internal_static_soy_Requirement_descriptor.getNestedTypes().get(2);
    internal_static_soy_Requirement_BannedFunction_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_soy_Requirement_BannedFunction_descriptor,
        new java.lang.String[] { "Function", });
    internal_static_soy_Requirement_BannedRawText_descriptor =
      internal_static_soy_Requirement_descriptor.getNestedTypes().get(3);
    internal_static_soy_Requirement_BannedRawText_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_soy_Requirement_BannedRawText_descriptor,
        new java.lang.String[] { "Text", "ExceptInHtmlAttribute", });
    internal_static_soy_Requirement_BannedHtmlTag_descriptor =
      internal_static_soy_Requirement_descriptor.getNestedTypes().get(4);
    internal_static_soy_Requirement_BannedHtmlTag_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_soy_Requirement_BannedHtmlTag_descriptor,
        new java.lang.String[] { "Tag", "WhenAttributePossiblyPresent", });
    internal_static_soy_Requirement_BanXidForCssObfuscation_descriptor =
      internal_static_soy_Requirement_descriptor.getNestedTypes().get(5);
    internal_static_soy_Requirement_BanXidForCssObfuscation_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_soy_Requirement_BanXidForCssObfuscation_descriptor,
        new java.lang.String[] { });
    internal_static_soy_Requirement_Custom_descriptor =
      internal_static_soy_Requirement_descriptor.getNestedTypes().get(6);
    internal_static_soy_Requirement_Custom_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_soy_Requirement_Custom_descriptor,
        new java.lang.String[] { "JavaClass", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
