// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: src/main/protobuf/conformance.proto
// Protobuf Java Version: 4.28.2

package com.google.template.soy.conformance;

public interface ConformanceConfigOrBuilder extends
    // @@protoc_insertion_point(interface_extends:soy.ConformanceConfig)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .soy.Requirement requirement = 1;</code>
   */
  java.util.List<com.google.template.soy.conformance.Requirement> 
      getRequirementList();
  /**
   * <code>repeated .soy.Requirement requirement = 1;</code>
   */
  com.google.template.soy.conformance.Requirement getRequirement(int index);
  /**
   * <code>repeated .soy.Requirement requirement = 1;</code>
   */
  int getRequirementCount();
  /**
   * <code>repeated .soy.Requirement requirement = 1;</code>
   */
  java.util.List<? extends com.google.template.soy.conformance.RequirementOrBuilder> 
      getRequirementOrBuilderList();
  /**
   * <code>repeated .soy.Requirement requirement = 1;</code>
   */
  com.google.template.soy.conformance.RequirementOrBuilder getRequirementOrBuilder(
      int index);
}
